### ISSUE TITLE
Enable minimization to system tray on Linux

### ISSUE THREAD

**Issue by saraneth0o** [tutao/tutanota#1041]
I can only see one other report for this and it's regarding Windows and has been closed.

On Linux I see there is now a system tray icon but it will not minimize to tray. It stays on the task bar.

**Comment by ganthern** [comment]
I'm sorry, I meant what _desktop environment_ you're using. Mint comes with Mate or Cinnamon. The problem on Linux is, that there's no standard tray and on some DEs there is none at all, that's why this takes a while to get right.

I also noticed that you deleted the Issue template, which is there to make sure stuff like this is answered right away.

**Comment by saraneth0o** [comment]
Oh, my bad, sorry. Didn't mean to delete it. I am using Cinnamon.

**Comment by ganthern** [comment]
aeef49be5002fea57cbba3ec7d12d39a34e55916
