### ISSUE TITLE
[feature request] show an indicator on folders that have "new" mail

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1042]
Related to:
- https://github.com/tutao/tutanota/issues/234
- https://github.com/tutao/tutanota/issues/573

It would be nice to have a "new mail" indicator show up next to folders that have just received new mail. The indicator (eg. underlined text, asterisk, inverse text) would stay "on" until the folder is clicked.

This is separate from #234, but could be used in conjunction with it.

This was mentioned on [uservoice](https://tutanota.uservoice.com/forums/237921-general/suggestions/36435871-better-inbox-managing) so it can be voted on!

**Comment by ganthern** [comment]
Hey andy,
this issue tracker is meant for bug reports and our internal organization, that's why the templates (which you seem to have conveniently misplaced :wink:) don't include one for feature requests. Those can be posted and discussed reddit (https://old.reddit.com/r/tutanota)

We're working on the unread mail counters, making it obvious where a new mail went shouldn't be too hard once that works.

**Comment by andy5995** [comment]
Understood ;)
