### ISSUE TITLE
Better contact integration on Android and iOS

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1066]
I want to use my contacts from the dialer app :+1:

**Comment by blaubachn** [comment]
Which of these is meant by this statement?
a) Tutanota contacts will sync with the system contacts
b) Tutanota will be able to access system contacts
c) The dialer will be able to access Tutanota contacts

**Comment by charlag** [comment]
If you enable this, Tutanota will act as a contact provider so that contacts would be accessible like all other contacts like in address book and dialer.

**Comment by valmar** [comment]
Any of these two a) and c) would be fine for me. But @charlag is right, that would be the best solution. Also this could apply to the calendar, once it is released!

**Comment by dkanada** [comment]
@nathanblaubach is there any official stance on which route the app will take? I'd like to eventually deprecate my current CalDAV server for a different solution, but if option C is planned for the future I will happily wait to move my contacts and calendars here.

**Comment by charlag** [comment]
@dkanada it's closest to c

**Comment by Jaaaarne** [comment]
Is there any approximate timeframe for implementing mobile integration for Contacts? With introduction of Calendar TN starts looking more interesting, but on a mobile Contacts integration is very important. Otherwise, personally, people won't be able to reach me via phone. :)

**Comment by Foxh0und** [comment]
Is there any update on this? 

Cheers,
Adam

**Comment by BenAlexanderAU** [comment]
Nearly at the one year anniversary of this feature request... Any update on this?

Cheers

**Comment by fabianski7** [comment]
Maybe something like https://github.com/etesync/etesync-dav is a start to solving that problem.

**Comment by pfertyk** [comment]
This would be a fantastic feature to have. Tutanota on mobile (at least on Android) works quite well in terms of a calendar, it just took me a moment to get used to not using a standard calendar widget. I can also quite easily make calls using Tutanota (clicking on a phone number in contacts redirects me to the Phone application). However, not being able to see the corresponding contact for incoming calls is a serious problem. I don't want to memorize each number, that's what the contacts are for ;)

If the integration between Tutanota and mobile calls is improved, that would make user experience much better in my opinion. Right now, I still have to use the Android contacts together with Tutanota, and I would like to switch to full Tutanota.

**Comment by dermitdemdino** [comment]
Problem:
Not only the contacts but also the calendars should be better integrated into Android and iOS. 

Example:
For example I have 2 mobile phones and a tablet. On one device I need email, on the other two devices only contacts and calendars.

Solution:
Could be quite simple, you would only have to add a switch in the client to turn email / contacts / calendar on or off.

**Comment by nvhaver** [comment]
Hi all,

I also would love to see this feature, although I do have some questions regarding security. Tutanota is all about security and privacy which is especially evident from the current implementation of the contacts feature (among others). In order to integrate with the Android system, a so-called [Sync Adapter](https://developer.android.com/guide/topics/providers/contacts-provider#SyncAdapters) would need to be made. This would then allow syncing contacts to the Android Contact Provider. 

My questions:
* Does the Android Contact Provider offer sufficient security? 
* Is it up to the user of the device to ensure it is encrypted and protected (passwords, biometrics, etc.)? 
* Would it be useful to include a warning message in the Tutanota application when the contact sync feature is used for the first time to highlight this issue?

I want to prevent that users get a false sense of security and would blame Tutanota when things go wrong.
These questions of course also apply to other features like calendar sync.

In terms of priority for this issue, I am a firm believer of the mentality that the main purpose of Tutanota should come first, namely secure email. That being said, these kinds of features could make the application more appealing to a larger audience due to increased ease of use. It's up to the team to decide on which growth strategy they prefer.

@dermitdemdino, I agree that it would be nice to have switches to disable or enable certain features of the app, but I feel you should put this into a separate GitHub issue as a separate feature request (if it does not exist yet). Such a toggle switch could (and should) be implemented separately from this issue and would take less effort (imho) as there are less security concerns involved.

Thanks for creating an awesome product!

**Comment by dkanada** [comment]
> Does the Android Contact Provider offer sufficient security?

Kind of but not really. It's not encrypted separately from the rest of the information on the phone to my knowledge, but it does require root access to bypass the Android SDK and open the database. Any app that includes the `READ_CONTACTS` or `WRITE_CONTACTS` permission can read this information when granted by the user.

> Is it up to the user of the device to ensure it is encrypted and protected?

I would say 100% yes because there's no way around the above security flaws. Encryption is becoming a standard on many Android phones which protects against external access, but insecure apps from the Play store are often overlooked in these situations. One alternative is running some apps in a work profile, but that can be cumbersome as well.

> Would it be useful to include a warning message in the Tutanota application when the contact sync feature is used for the first time to highlight this issue?

I would consider a warning sufficient to explain the possible pitfalls of syncing contacts to Android or iOS phones. I would also consider it fine to simply enable the feature, because sync is integral to the utility of said data. Some people are probably using Google for contacts and events for that very reason. Calendar events can still generate notifications from Tutanota (although that does limit one of the main benefits of Android which is user choice) but phone numbers are definitely useless when they aren't on your phone.

**Comment by yann-soubeyrand** [comment]
I would also love to have a Tutanota Android provider which would give access to my emails, contacts and calendar to my current email, contact and calendar apps without having to install the Tutanota app. Microsoft Exchange integration seems to work like that: a provider adds an option to create an Exchange account on the phone and then the emails, contacts and calendar are synced and accessible from the apps on the phone.

**Comment by charlag** [comment]
@yann-soubeyrand Exchange has no e2e encryption, Tutanota cannot and will not work as CalDav but we can do contact integration through our app

**Comment by pfertyk** [comment]
Just to clarify: I think it would be quite OK if Tutanota didn't synchronize completely with Android. I get that using Tutanota email and calendar like normal Gmail and Google calendar would be convenient, but I would be absolutely OK with using a custom Tutanota calendar widget and checking emails in the Tutanota application. I am also completely fine with making a phone call using Tutanota contacts, since I can easily browse them and find the one that I need.

The only serious problem right now is that for incoming calls, I cannot see the name of the contact. I could manually copy the contacts from Tutanota to Android, but that's very inconvenient. Would it be possible to intercept the incoming call in Tutanota and just show the name of the contact? Could e.g.Tutanota replace the default calls application or at least show a notification when a call starts with the name of the contact? All other integration stuff is about making Tutanota work more seamlessly with Android, and I think that it's not necessary and, as mentioned, can collide with Tutanota's privacy concerns. However, showing the incoming call's contact is kinda important and the only thing that makes Tutanota contacts not fully usable.

**Comment by tukusejssirs** [comment]
As for the contacts, an alternative to contacts sync’ing with Android (or any other OS) would be a call app (call manager if you wish). That way all the contacts (incl call log) would be e2ee with Tutanota infrastructure. Of course, that might be more difficult to program than creating an Android Contact Provider, however, when we look at it that we need a separate contact provider for each OS (Android, iOS, Librem 5 / Linux, Windows, macOS), I think my proposal is a better one.

**Comment by yann-soubeyrand** [comment]
> @yann-soubeyrand Exchange has no e2e encryption, Tutanota cannot and will not work as CalDav but we can do contact integration through our app

@charlag sorry if I wasn't clear. I thought about providing android contacts and calendar providers (not sure if this is the right terminology) so that everything can be end to end encrypted from the servers to the phone and seamlessly integrate with other applications on the phone making use of contacts and calendar (like the call app for example, or other mail applications which would be able to add appointments to the calendar). Maybe a similar approach can be taken for the mails too, though this is less important than contacts and calendar I think.

**Comment by freedriven** [comment]
This is a "must have" for me to move to a paid Tutanota (along with email import).
In my case, Tutanota acting like a contract provider to the phone would be fine. Bottom line, whichever dialer I am using on the phone needs access to the Tutanota contact list.
Subscribed for hopeful updates.

**Comment by Grannath** [comment]
Same here, I really don't want to sync my contacts with Google. I'm not an expert for Android, but I could contribute to the Android implementation if you need support. I have 0 Apple devices though, can't help much there.

**Comment by Macqael** [comment]
any news on this ?

**Comment by g00nix** [comment]
This is definitely a must-have. I will buy the service if this option is available, as it allows you to use LineageOS as a google-less phone by using tutanota for contact management.

**Comment by Neurochocolate** [comment]
Definitely need this option so I can disable the last bit of iCloud. Tutanota, can you give us some piece of mind and tell us what the current status is?

**Comment by B3K-me** [comment]
I'm trying to find encrypted email, calendar, and contacts for Window, Android and optionally Linux.  Sadly this is the closest I have come.  

Anyone have an update?

**Comment by freedriven** [comment]
I did notice this got added to the "planned" phase of the roadmap. 
https://github.com/tutao/tutanota/projects/2

I don't think they're going for wide acceptance at this time. That would mean contact (and likely calendar) integration, ability to import current email/calendar/contacts, and use of user defined domain names. Basics.

**Comment by bedhub** [comment]
We will track this now here. It will be one of the first things we want to improve in 2024. https://github.com/tutao/tutanota/issues/6374
