### ISSUE TITLE
Pictures can't be pasted into the editor

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#110]

**Comment by armhub** [comment]
Related to #609

**Comment by laurette75france** [comment]
Hello community and Tuta developers and Roadmap-decision makers :

 it is ESSENTIAL that we be able as entrepreneurs to send secure emails YES but also nice-looking ones.  So could you please add to the next releases an update on the rich text editor so that we can customize our emails not only with links and edited text **but with images to make them ATTRACTIVE. **This is basic and essential as far as communication efficiency and BUSINESS EFFICIENCY for me as an entrepreneur** 

I was very happy with the rich text editor evolution, It was needed too! I think that as the reference for secured emails, now the next step is to be able to provide the possibility to make our emails as good looking as possible as do other top notch email solutions.
 
I wrote to your Helpdesk to communicate this request and they indicated this issue-threadline and said that it was not planned as a future improvement yet. Is is somewhere in the pipe ? It seems  a very basic feature (which does not necessarily means technically easy to set up I can understand this) but so important as far as customers'attractivity for you ( a major asset to sign up new clients on your side) and a major need on our side as customers and business people.

Hoping to get a feedback from you and tons of comments from the community :))) This is somehow a blocking point for my current communication and I really hope that it evolves in the future. 

Regards, have a great day
Laurette

**Comment by charlag** [comment]
We know that it is an important feature and  and we certainly have this feature planned, it's tracked as #609 as said in comment above
You can always check our roadmap here:
https://tutanota.com/roadmap/

**Comment by laurette75france** [comment]
Thanks Charlag for the very quick reply! I'm excited that this is planned !!  I can't seem to figure out **when** this is going to be released though. Is it indicate somewhere in the issue pipeline ? At the link you indicated I can indeed see alll te items whichare planned and tagged as "new feature" but I cannot manage to see the dates / month at wich each of the item will be available to us. 

Could you be a bit more specific on the release date or month for this 609 item ? Many thanks, Have a great day !

Laurette

**Comment by charlag** [comment]
We don't give any time estimates, sorry, it is mostly pointless at this scale. We prefer to only give promises we can fulfill.

**Comment by laurette75france** [comment]
Ok thanks Charlag for your transparency and feedback, i do appreciate this :) And I also understand that you might not be a huge crew of developers and that things have to be taken one by one by order of necessity and according to your own global business roadmap too.

If I can share a suggestion then : indicating a priority order in this list so that we can as customers have an idea of what will probably come before what as a set priority on your side. I would say for example that being able to add images in our emails to make them pleasant and impactful is a bigger priority than having an "out of office" automatic message or subfolders to store our emails, as it creates a heavier added-value (addressee-centric and not just sender-centric) in our using of the solution. I know this is a personal point of view only: ) I truly think that for both sides (ours and yours) this is a major asset to achieve as priority 1 though. 

Well, I think my message went accross and I now keep my fingers crossed to be able to send top-classy beauuuutiful emails to my clients soon with Tuta ;))) Thanks again for all your work and for providing an efficient emailing solution :))))

Cheers,
Laurette

**Comment by vitoreiji** [comment]
Could not reproduce, probably solved along with some other fix.

**Comment by Zadok33** [comment]
Hello, I recently switched to Tutanota and was disappointed I couldn't paste images into my emails. Neither via the Web or Windows client. It would be great to see this added in a future release.

**Comment by benjaminrich** [comment]
+1

**Comment by torhovland** [comment]
Just signed up for Tutanota and immediately discovered this issue. It's a deal-breaker for me, unfortunately.

**Comment by charlag** [comment]
@torhovland could you elaborate? It should work

**Comment by torhovland** [comment]
> @torhovland could you elaborate? It should work

![image](https://user-images.githubusercontent.com/55164/167367099-e22471d9-48d3-44ff-b4a0-9b792f87f9f9.png)
