### ISSUE TITLE
iOS - Force refresh on new version

### ISSUE THREAD

**Issue by geocfu** [tutao/tutanota#1100]
**Bug in mobile app**

**Describe the bug**
When a new version is pushed, if the mobile app was recently opened and stayed in ram or recently opened and left ram but after reopening the app continued from where it left, a refresh is not happening. So, while the new version might have been updated on the desktop client or to the web version, the mobile app still continues to behave on the previous version, in result, we might have inconsistencies like the fixed inbox rules on 3.47.1 being reverted back #1073 .

**Expected behavior**
A force refresh on all clients upon a version update.

**Smartphone (please complete the following information):**
 - Device: iPhone 5s
 - OS: iOS 12.1.3
 - Version 3.46.3

**Comment by charlag** [comment]
Hey
This is not a bug. We load the app from the app files and not from the web for performance and security reasons. We will release app update soon. They're always lagging behind a little bit but this time we found some bugs we needed to fix so we skipped one mobile release.

**Comment by geocfu** [comment]
Well, in that situation, why don't you trigger an update through a push notification?

Just like when a new mail is being received, a push notification is triggered, when an update is available, why not to update the app's files in the background using the push notification as a way to trigger the update, behind the scenes.

**Comment by charlag** [comment]
Because the app is not purely web app, there's a possible mismatch between native and web parts. It is just a whole new level of complexity, not speaking of securely downloading it and allowing to execute downloaded code (when you allow your app to mutate itself things get *fun*). And the benefit is not so large: we would be able to deliver the app few hours earlier.
Most delays with mobile apps are caused by additional testing and our current build infrastructure being kinda lacking (we're working on that).
If you wish to have instant updates, pin mail.tutanota.com to your home screen.

**Comment by geocfu** [comment]
Thank you very much for the effort you put to explain the situation.
Keep up the good work!
