### ISSUE TITLE
Mailbox Search is not enabled

### ISSUE THREAD

**Issue by anothernewb** [tutao/tutanota#1194]
**Bug in web app**
There was a search function that never worked, and now it appears to be gone altogether. I really want to adopt this client full time but not being able to search through thousands of emails is literally a NO-GO for me (and I'm sure thousands of other potential users). 

I don't understand why this conflict exists? Why do we need cookies to search when gmail and yahoo and hotmail do not? I don't even have those sites whitelisted and search works fine.

**Describe the bug**
Previously I would try to search and it said I did not have cookies enabled. I Use firefox with Strict Content blocking and "do not track" but the tutanota domain is whitelisted so it *should* allow cookies. 

**Desktop (please complete the following information):**
 - OS: Win10
 - BrowserFirefox
 - Version 66.0.1 (64-bit)

**Comment by charlag** [comment]
Hey
First of all, we don't need cookies. We don't use cookies and they're unrelated to the search.
Second, we need storage on your device to be to index mailbox. You're trying to compare us to the Gmail an Yahoo but those are not encrypted mailboxes, they *can* read your emails and they use it to index your mailbox on their servers. We cannot do that because we don't have access to it. So we download all the things you may need to search, strip it into words, encrypt it and put it into your device, there's no way around that.

From your report I could only infer that something with search doesn't work for you. Please be so kind to describe in the clear manner what you're trying to do and what is happening (somehow like in the issue template).

**Comment by anothernewb** [comment]
Ok sure that makes sense about the way the search functions.

Now I don't see the search button at-all, did that get changed to a paid feature? I have not purchased membership as things were not working correctly...

![Untitled](https://user-images.githubusercontent.com/49032841/55166938-4a185e80-512d-11e9-94b6-dd29fad3beb3.png)

**Comment by charlag** [comment]
It means that we cannot open browser storage for one reason or another. Most likely it is one of your add-ons. Please try to disable them or even better try the "safe mode":
https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode

**Comment by anothernewb** [comment]
Thanks for the suggestion charlag, I went ahead and booted Firefox in safe mode and it had no effect on the search bug. Note that there are no add-on icons in the top right. Any other ideas?
![safemode](https://user-images.githubusercontent.com/49032841/55414445-f9837580-551f-11e9-806b-20f26e190d8c.jpg)

**Comment by charlag** [comment]
Well it still says "blockable content detected on this site" but I have no idea why, there are no cookies whatsoever. Try disable blocking and try again, at least to test it out.

**Comment by charlag** [comment]
Feel free to reopen if you believe that it's an issue with us but I'm pretty sure that the storage is somehow disabled.
