### ISSUE TITLE
[iOS] The app not receive push notification when running through xcode

### ISSUE THREAD

**Issue by smaroff92** [tutao/tutanota#1196]
Hello!
I install iOS app from xcode and the app not receives push notifications.
But installed from Appstore is received push notifications.
What I need to do to enable it?

**Comment by charlag** [comment]
Hi!
I'm afraid that's not really possible and I would blame Apple here. The situation is the same across all apps.
The problem is that it is designed in a way that client and server must match. I suspect that when you build it you use your on Apple credentials so they don't match ours.
Because Apple restricts background usage we cannot build our own home-brewed notification system like on Android. 
One possible solution is to setup email or SSE notifications to your own server and from there forward it to Apple with your credentials.
Another possible solution is to modify iOS client that it wakes up in the background and checks for new emails somehow but that's quite tricky.

**Comment by smaroff92** [comment]
Thank you for response!

<< One possible solution is to setup email or SSE notifications to your own server and from there forward it to Apple with your credentials. >>

Can you tell about it more? Where I must make change in Tutanota?

**Comment by charlag** [comment]
You can set up email notifications from Settings->Mail->Notifications.
If you want to try out SSE route I recommend you to check `DesktopSseClient` or Android client.

**Comment by smaroff92** [comment]
ok, spasibo!
