### ISSUE TITLE
Updating Windows app sometimes just uninstalls

### ISSUE THREAD

**Issue by iinfin** [tutao/tutanota#1413]
**Describe the bug**
Sometimes updating desktop app on Windows (didn't test other OSs) ends up only uninstalling and not installing new version.

**To Reproduce**
1. Click on update notification to restart
    - Or quit app after receiving update notification
2. Uninstalls the app but doesn't install new version

**Expected behavior**
Install the new version :)

**Desktop**
- OS: Windows
- Version: 3.57.3

**Additional context**
This happened at maybe around 3/4 of the updates in the last few months. But seems like sessions are stored so not completely uninstalled. After I install it manually with the [latest installer](https://mail.tutanota.com/desktop/tutanota-desktop-win.exe), it just logs in as always.

**Comment by soyouonly** [comment]
I have experienced same issue but I seem to recreate it with the following steps (3.57.5 on Windows 10 Professional):

1. Open system tray and right click the Tutanota icon (regardless of having received update notification)
2. Select Quit
3. Application closes, then uninstalls. Need to reinstall application but profiles remain.

**Comment by igorpupkinable** [comment]
I am experiacing the same issue for last few months.
I click update notification, application quits and uninstalls.
It never install updated version back.

I am glad to debug if someone can tell me how to do it.
My only guess so far is that I am installing desktop app for all users with requested admin persmission to be able to change content in `C:\Program Files\`.

**Comment by charlag** [comment]
Reported by some users still.

**Comment by charlag** [comment]
@igorpupkinable if you could run installer from the command prompt and check if there's any useful info there, it would help us a lot.

**Comment by ganthern** [comment]
we're not getting any reports for this anymore

**Comment by boistordu** [comment]
Hi Team,

Why is it still occurring?Do I need to make a support ticket? 
I was hoping that was just a glitch a few version back because you fixed it for a moment the now it came back at every single iteration of your soft for every single windows hosts that I have.
You succeeded to fix it so why it is now impossible to fix it? Especially since other people are using exactly the same installer and are not having the same problem? 
Do we know at least why it is happening?

**Comment by charlag** [comment]
So if it is still occurring we can reopen it but currently we don't know why or how it happens. It might be related to the missing Admin privileges on update but we failed to reproduce it so far.

**Comment by bedhub** [comment]
This is still reported when the application is installed for all users.  We should find a solution for this case.

**Comment by bedhub** [comment]
One user installed the program in a different folder and again for all users:
Folder path: C:\Users\Public\Documents\Local Programs\Tutanota Desktop

**Comment by boistordu** [comment]
Guys, update to 3.70 it's still happening.... I've made even a mail to the support about it for the previous version.
It's happening to all on my hosts and again always because of the same option, installation for all users.
The uninstallation process is going fine but then the process stopped and the file is still C:\Users\boistordu\AppData\Local\tutanota-desktop-updater\pending

So are we sure that it is resolved? Is it possible that it is because of an overwriting of the updater?

**Comment by ganthern** [comment]
Hi @boistordu,
it's expected that the update to 3.70.0 would still be broken, since 3.70.0 was the first version that contained the fix.
Don't hesitate to complain if it happens from here on out!

**Comment by boistordu** [comment]
Same thing happening again for 3-4 updates now.....

**Comment by charlag** [comment]
Installer/uninstaller is an atomic unit for us. We don't call "uninstall" and then "install" after that. This means that something inside the installer itself fails.
What happens if you manually install old version and then run installer for the newer one?
I'm pretty sure it's some nasty permission problem and we need some info on how to reproduce it, otherwise we can't do anything.

**Comment by charlag** [comment]
The problem is that I changed this commit:
https://github.com/tutao/tutanota/commit/c4b12e95928dc9baffa20ef835953dd08f850e88

**Comment by charlag** [comment]
I've made a fix but I would like to get to the bottom of this. I tried running installer manually with log statements and /S but output is somehow detached and I don't see it.

**Comment by charlag** [comment]
Test notes:
- [ ] Install app system-wide on Windows (there are old installers). Let it update. See that it's still there.
- [ ] No auto-update on quit on Windows
- [ ] Updater still works on other platforms (especially on quit)

**Comment by johnbotris** [comment]
The update notification on windows still says it will update on quit

**Comment by charlag** [comment]
Funny enough, the German one was already fine
