### ISSUE TITLE
Remove or change single event of recurring events.

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1475]

**Comment by Backspaze** [comment]
When you've added the functionality for Sending/receiving calendar invitations (#1355),  removing/rescheduling a single occurrence (or, of course, an entire series) should also prompt for sending an update to the invites about the canceled/rescheduled meeting.

**Comment by Tomjans** [comment]
Hi, I notice that this issue is still open, I don't know if it is planned to be fixed regardless of whether it's an invited event or not? 

I cannot simply remove or alter a single occurence of a repeated event in the calendar. If I do delete such an event, all repetitions, including those of previous days/weeks, are deleted. For example, if I have a weekly meeting at a certain time, planned and repeated each week in the calendar. And say I am on leave or sick at a certain day, I cannot delete (or alter) that single occurence without deleting (or altering) the whole sequence.

(correct me if this is not where I should pose this question)

**Comment by oftrepeated** [comment]
Hi! Could we get an update on this feature? [This Reddit thread](https://www.reddit.com/r/tutanota/comments/s6alq6/feature_request_add_the_ability_to_delete_a/) led me here, but I can't tell if this is actually on the roadmap as the comment in the thread indicates. This is a hugely necessary and important feature. Thank you!

**Comment by Backspaze** [comment]
@oftrepeated this issue sounds very similar to #4860 and that issue is included in [the roadmap](https://tutanota.com/roadmap). Perhaps this issue should be closed as a duplicate of #4860?

**Comment by oftrepeated** [comment]
@Backspaze Yeah, that makes sense, though it might be good to clarify that #4860 also includes deleting individual occurrences. Thanks for pointing out the similarity, and for the link to the roadmap.

**Comment by vitoreiji** [comment]
> @Backspaze Yeah, that makes sense, though it might be good to clarify that #4860 also includes deleting individual occurrences. Thanks for pointing out the similarity, and for the link to the roadmap.

It does not include deleting individual occurrences. That is covered by #4859, which is even higher on the roadmap.

**Comment by vitoreiji** [comment]
This has been split into #4859 and #4860.
