### ISSUE TITLE
Search result shows triplicate results for same email

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1523]
1) Enter email search mode and enter string to search
2) Delete several emails from 1) search results window - emails disappear appropriately
3) After the 10th or so delete, additional delete attempts fail without any error indication.
4) Close and re-open search field, re-attempt search string and deletes - now triplicate emails are displayed in the inbox and email deletes continue to fail without any error indication.

**Comment by charlag** [comment]
How to reproduce search not reacting to delete events:
1. Search from mail view so that there's an overlay
2. Delete mail not in the first 10
3. No reaction

What is happening is that we check `locator.search.result()` but it doesn't contain anything besides first 10 results in this case because loading more results is done not via `searchModel` but directly via worker and it doesn't have additional results.
