### ISSUE TITLE
App shows FILE_NOT_FOUND error when opening link

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1538]
> When I try to open an email link reiceived in a newsletter, tutanota opens a page error msg. The problem is that I cannot get anywhere from the page. I have only my phone's back button visible but nothing happens and I cannot get anywhere with it. I have to close the app by swiping upwards and re-open tutanota app.

This happens if the link is a relative link, we should prevent opening relative links within the app.

**Comment by bedhub** [comment]
fixed by 8f9307e5

**Comment by bedhub** [comment]
within the app clicking on relative link redirects to the login screen now

**Comment by vitoreiji** [comment]
Only reproducible on iOS.

**To Reproduce**
1. Get an email with a relative link, such as `<a href="/test">relative</a>`
2. View the email on iOS client
3. Touch the link
 
**Expected behavior**
Nothing happens.

**Actual behavior**
User is logged out and taken to login screen.

**Smartphone**
 - Device: iPhone7
 - OS: iOS 13.3
 - Tutanota App Version 3.64.3

**Additional context**
On the Android and Desktop apps, trying to open the link does nothing.
