### ISSUE TITLE
Why the industry-standard 256-bit AES encryption was not chosen?

### ISSUE THREAD

**Issue by Lucas-Developer** [tutao/tutanota#155]
**Why the industry-standard 256-bit AES encryption was not chosen?**

https://tutanota.uservoice.com/knowledgebase/articles/470732-what-encryption-algorithms-does-tutanota-use

**Comment by mpfau** [comment]
The performance on mobiles was not good enough for AES-256 and RSA-4096 when we started in 2011. This has changed in the meantime and we will increase the strength of our algorithms in future.

**Comment by Stele77** [comment]
Hi!
Now that one year has passed, this is the one concern that holds me back from switching from protonmail.
Can you provide a timetable when to expect this?
The whole service is useless without a strong encryption, and AES-256 would be still considers safe as of today, opposed to 128 Bit which is not AFAIK..

**Comment by charlag** [comment]
Hey
We still have plans to upgrade but this is not a simple task, obviously.
We use AES-256 in our new recovery code functionality for example.

**Comment by mpfau** [comment]
Regarding security of AES-128: All organizations that make suggestions for symmetric key lenghts assume that AES-128 is secure for at least a decade.

The only reason for us to upgrade to AES-256 is to make Tutanota post quantum secure. However, AES-256 is only one part of that upgrade as we also have to improve asymmetric encryption (RSA is not enough).

**Comment by Stele77** [comment]
Thanks for the reply! 
I hope you understand, that still many users like me would prefer if they could choose the "best" possible solution that is possible and still manageable in this context.
Even more when one understands how trust of us "ordinary" tech enthusiasts has been lost into the integrity of those standard making organisations you refer to since the snowden leaks, and judging from previous publicly documented cases where US agencys tried to influence proposed encryption standards. 

We are soon 10 years after 2011, and AES is now accelerated in hardware on allmost all Android phones, besides only the very cheapest sub 100$ Anndroid Go models. On those you could fall back like google does on other alternatives.
Also on X86 and AMD64 archs it is accelerated in hardware for many years, so AFAIK it should not have a (big) additional costs for your systems. 

Seeing what is now happening to Assange will make it even more nessecary for future leakers and activists to have total confidence in their privacy, even though total privacy will always be impossible. 
Still, when you try to protect activists and journalists from state actor level attacks on their privacy, for them it can be of deadly consequences even if their communications can be decrypted in 10 or more years... 

And maybe today as no one know what kind of hardware and software solutions the NSA can rely on with their billions of yearly financing and 1000s of the most skilled crypto experts. 
While with opting for the best possible option today, you may prevent this, and at least would have done all you could.

I know it is a hard decision to make, as it would take quite much developer time and resources to achieve this, but it would still be important for many current or possible customers.. 
Even if it would "only" be a small, still theoretical value, or of marketing value, and to not loose out a major "pro" when compared to competing services like ProtonMail, and to protect those clients that are especially endangered because of their profession or activism.
Thanks for your reply again,
Kind regards
