### ISSUE TITLE
Recipient can see other encrypted mail that was for another recipient

### ISSUE THREAD

**Issue by BuZZ-dEE** [tutao/tutanota#1582]
I sent an encrypted email to an recipient and also to me in CC. If I open the private link and enter the password, I can see another private encrypted email, which I sent a few weeks ago to another recipient. I tried  to contact you by [phone](https://tutanota.com/de/about) in this case, but no one took of the phone. Do you have an emergency number for such cases?

**This is big security issue.**

**Comment by vitoreiji** [comment]
If I understand correctly, you have CCd your external email address in both emails and you can see the first message from the link in the second message. This is correct, because we create one mailbox per combination of Tutanota sender and external recipient.

So, to be clear:

* you have a Tutanota accout T, an external email E, and two friends A and B
* you send message M1 from T to A and E
* you send message M2 from T to B and E

A sees only M1. B sees only M2. E sees both M1 and M2.

Please confirm if this was the case.

**Comment by BuZZ-dEE** [comment]
Yes, you correct. I had a little bit panic. 😉 I didn't know that it works like that.
