### ISSUE TITLE
Allow custom themes

### ISSUE THREAD

**Issue by ryanpcmcquen** [tutao/tutanota#1621]
Since the JS files just read a few colors, it'd be nice if the app supported custom themes, with a set of 5 colors or so that are set under the Appearance menu.

**Comment by charlag** [comment]
Hi
We don't accept feature requests here.
What you are asking for is available with Whitelabel.

**Comment by ryanpcmcquen** [comment]
@charlag, I signed up for Whitelabel but it isn't working on the iOS app.

**Comment by charlag** [comment]
@ryanpcmcquen indeed, it does not work for mobile apps currently and maybe we should change this instead.

**Comment by ryanpcmcquen** [comment]
Can we change this bug @charlag?

**Comment by charlag** [comment]
I found https://github.com/tutao/tutanota/issues/1437 and it seems like custom themes work on Android, I'll check it

**Comment by armhub** [comment]
Custom themes are bound to a whitelabel domain, therefore they do not work in the mobile apps or desktop clients. The reason is that before logging in we would not be able to know which theme to show.
The only exception is while configuring your custom theme colors. When saving colors in a mobile app or desktop client you see your custom theme colors in Tutanota. This allows you to check your configuration. But as soon as log in out and in again the default colors are shown again.

**Comment by ryanpcmcquen** [comment]
That defeats the whole purpose for me.
