### ISSUE TITLE
Inbox rules are not processed in the background

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#165]
Currently the inbox rules are only processed when the inbox folder is selected. Inbox rules should be processed in the background even when another folder or view is selected. After login we only load a fixed amount of emails which are then processed by the inbox rule handler. This does not guarante that all new emails are sorted correctly. 

- process inbox rules in worker thread
- store the last processed mail and load all new emails from this mail after login
- when changing the inbox rules in the settings add an option to process the inbox rules again for a given amount of emails (e.g.first 100).

**Comment by snaggen** [comment]
This is kind of annoying... A typical scenario that happens to me a lot, is that I have some folder where I expect mails, since I'm having a conversation with someone. 
So I have my folder "Misc" open since I have been reading a ISP-support mail and replied to that. I then get a reply, that is supposed to be filtered to the Misc folder. I now get a notification about this new mail, and the Inbox get a label saying it have one new mail. I then have to click on the inbox folder, just to find it empty but now the Misc folder (which I just had open) have a new mail label. So then I have to go back to the Misc folder and read the mail.

**Comment by bedhub** [comment]
does not apply inbox rules after log in
