### ISSUE TITLE
Allow lenient formatting for captcha

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1741]
E.g. accept missing leading 0

**Comment by armhub** [comment]
also accept 12 hour format

**Comment by Philimanjaroo** [comment]
Hello, I would like to have a look at it :-)

**Comment by jowlo** [comment]
@Philimanjaroo Thanks, very nice!

You can start looking at the `runCaptcha` function in `SignupForm.js`. Especially this is the line where we grab the input value and i think it would make most sense to modify here to a) always return the time between 00:00 and 11:59 (01:23 instead of 13:23) and b) also add leading zeros, s.t. we always have a `hh:mm` format with `hh` < 12.
https://github.com/tutao/tutanota/blob/8af78b6cb8de69a4c332a89fd48eb6cb92212ff4/src/api/main/SignupForm.js#L205

**Comment by Philimanjaroo** [comment]
Is there a way to test the code changes without doing a real registration for a new e-mail account? When I repeat the registration process with my modified web client too often, my IP gets banned for suspicious behavior.

**Comment by jowlo** [comment]
Yes, you are right, you would be blocked pretty quickly.
As the server is not open source, i would suggest writing a function that takes care of everything. You could test that easily without all the logic around it. 

If you make a pull request out of it, we can test it with local development servers.

**Comment by Philimanjaroo** [comment]
Perfect. I'll do that!
