### ISSUE TITLE
Dragged email is not visible in Safari

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1832]
As a user of Tutanota, I want to drag-n-drop emails from the mail list to folders in Safari. When I am dragging an email I want to see visual feedback: email which is being dragged and special cursor.

**Acceptance criteria**
Dragging non-first email from the list allows you to see the email and have mouse cursor indicating dragging.

**Impl hints**
Safari 14 only shows parts of the first email in the list, Safari 15 shows first email and icons from other emails.
This probably has something to do with translation of elements.

-----

Drag & drop of emails is only possible for the first element in the mail list. For other elements the drag & drop effect is not visible.

Below I describe the steps to replicate the problem:
* Place yourself on a folder containing more than one email.
* Select an email and drag it to another folder.
* The drag-and-drop effect no longer allows you to see the email you are moving and therefore it is difficult to see where you are going to place the email.

 - OS: macOS
 - Browser safari

**Comment by Vasd-Q** [comment]
Using Safari and then trying to ensure privacy/security is very ironic....

**Comment by rezbyte** [comment]
This issue is caused by Safari not handling `transform` when rendering the dragged element(s). I wrote a small test HTML file to test this hypothesis & it holds true. Unfortunately, all of our positioning for the list & mail rows are done exclusively with `transform`. This means to fix this on our end, we will need to rewrite the list & the mail rows entirely which may be too much work for such a small issue.
