### ISSUE TITLE
Japanese kanji are not Japanese

### ISSUE THREAD

**Issue by jernejp21** [tutao/tutanota#1909]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When writing in Japanese, kanji are changed. Also comma after kanji is placed in weird position. In previous versions this was working. In mobile and web application this is shown correctly. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Type this string: "背中、"
2. Here, the font is correct.
3. Please see picture below how this looks in desktop version. You will see that the first set (before comma) is different and comma is in the middle of text.

**Expected behavior**
If you save draft and open with web application, it will be displayed correctly.

**Screenshots**
![slika](https://user-images.githubusercontent.com/61543115/76693096-1cf8ef00-66a3-11ea-8d5e-84727b9bd9d4.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 3.69.2

**Comment by charlag** [comment]
Hi
Do you remember in which version it worked correctly?

**Comment by jernejp21** [comment]
I think in previous Desktop released version it still worked. Previous or 2 before 3.69.2.

**Comment by vitoreiji** [comment]
It looks like the Windows desktop client renders the characters using the "Microsoft JhengHei UI", whereas Chrome, for example, used SimSun on my test machine. This explains why the problem is Windows specific.

I don't know if this font is doing it the right way for some other context, for example, maybe that would be the correct thing to display for traditional Chinese text? See [the Unicode Han Unification](https://en.wikipedia.org/wiki/Han_unification).

**Comment by jernejp21** [comment]
Is this automatic process or can you specify which font to use? Windows have by default installed MS Gothic font for Japanese.

Or would be easier to implement font selection in Desktop client? The same way as Outlook or Thunderbird have font selection option.

**Comment by ganthern** [comment]
related: https://github.com/electron/electron/issues/18829
