### ISSUE TITLE
Windows app: clicking the update notification does nothing

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1930]
Should update the client.

**Comment by ganthern** [comment]
Could you check if there are actually two update notifications? I see this on Win 8 sometimes, and the first one doesn't seem to do anything.

If Win 10 collapses the notifications this will be difficult to check, though.

**Comment by ganthern** [comment]
I can't reproduce this atm (W8). When #1951 is merged, the problem with the duplicated update notifications/update download in unsigned builds will be fixed. I have a hunch that may play a role here, since one download thrashes the update cache while the other one is working on it.

If this occured in a signed production build, I'll have to further investigate this on W10.

**Comment by vitoreiji** [comment]
I had a hard time investigating this on W10 as well because the notifications are not stored in the notification tray. I saw this behaviour in a test build, not production.

**Comment by ganthern** [comment]
Then it _may_ just be fixed soon.

**Comment by ganthern** [comment]
closing as a dupe of #4472
