### ISSUE TITLE
Search bar in search view loses focus

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1931]
- Open search view
- start typing and wait for search result.
-> Search result column is focused

Expected: focus should stay in search bar to be able to enter more characters. Focus should switch to result list when pressing enter.

**Comment by charlag** [comment]
Seems like it was intentional but was not working:

https://github.com/tutao/tutanota/blob/f2956855b0730d300af9b8ba2bde49fdd3b93767/src/search/SearchListView.js#L86

https://github.com/tutao/tutanota/blob/f2956855b0730d300af9b8ba2bde49fdd3b93767/src/search/SearchView.js#L518-L520

I would probably just remove that but stable version just focuses <body> if you press enter which is also not perfect. At least receiving new search result should *not* focus anything automatically.
