### ISSUE TITLE
Show banners for missing or failed email authentication

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1986]
Remaining issues:
- [x] If there is a different technical sender, DMARC can not be checked and we show the info banner, it is not visible that the technical sender is a different address.
- [x] The info banner with the bold black text does not look nice. The original proposal was much better.
- [x] The FAQ entries for this and other banners are missing.

**Comment by vitoreiji** [comment]
With failing DMARC and SPF, I don't think it makes sense to display the technical sender at all, since this can also be spoofed. We should only display the envelope sender if it passes SPF with `identity=mailfrom` or display the helo domain if it passes SPF with `identity=helo`.


![Screenshot_2020-04-15 visfortest tutanota de - Tutanota](https://user-images.githubusercontent.com/197261/79327043-1795fb00-7f14-11ea-8d5e-029cb0a5fc3f.png)

**Comment by charlag** [comment]
We display technical sender only if it's missing authentication, not failing one. If SPF will fail you will get failing authentication banner.

**Comment by vitoreiji** [comment]
Is that the case on 3.71.2? The message from the example has failed DMARC and soft-failed SPF:
```
Authentication-Results: w1.test.tutanota.de (dis=spam; reason=dmarc);
	dmarc=fail (dis=spam p=quarantine; aspf=r; adkim=r; pSrc=config) header.from=gmail.com
Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=REDACTED; helo=example.com; envelope-from=spoofed@gmail.com; receiver=<UNKNOWN>
from:admin@gmail.com
subject: this message is spoofed
```

**Comment by charlag** [comment]
No, it shouldn't work like that, spf errors should be HARD_FAIL

**Comment by charlag** [comment]
The reason is that Gmail has DMARC policy `none` and we consider our default policy as the source.
We decided with @armhub to improve it after the release and add a server issue because it's still better than before.
