### ISSUE TITLE
U2F pops up automatically on Windows

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2044]
When logging in, we start listening for U2F devices automatically. On Windows this leads to the modal dialog from the system. After cancelling it, we show "unexpected error" and you can't log in with TOTP.
We need to change it to manual activation (like we do in settings) and handle cancellation properly.

**Comment by bedhub** [comment]
"unexpected error" is only shown in Firefox after cancelling the native dialog. I tested with Chrome and Edge browser and the return code is different (error code 4 instead of error code 1) which leads to the error "The security key has not been registered with your account". Both messages should not be shown in case of cancelling the native dialog.

I think that we should keep the behavior that we are waiting for u2f confirmation by default. In case of cancellation or and error (which is basically the same) we should not automatically try it again. Instead we should change the current message "Please authenticate with your..." to something like "Could not complete authentication request." and add a button "Try again" to start the process again.
