### ISSUE TITLE
Swiping between months on calendar causes Android app to lag and crash

### ISSUE THREAD

**Issue by MarissaRS** [tutao/tutanota#2102]
Whenever I try to swipe between different months on the calendar, it eventually will lock up and freeze my entire device (no system navigation works either). Then I get the "app not responding" message and the only way to fix it is to force close Tutanota. I'm basically unable to view future months since the app crashes before I can view them.

**Comment by charlag** [comment]
Hi, thanks for reporting
May I you to fill template details (your Android version/app version/manufacturer)? Does it happen each time you scroll between month or on some specific month?
Thanks

**Comment by marissarousseau** [comment]
Here my device info:
Google Pixel 3
Android 10 (GrapheneOS)
App Version: 3.73.1

The issue happens if I scroll left or right in the month view, and it doesn't matter which month I'm currently switching to or from, it locks up as soon as I try to switch it, then the app stops responding.

**Comment by marissarousseau** [comment]
I wanted to add some extra information. I do have quick a lot of different calendars, and calendar events which repeat on various rates. Perhaps the app is freezing/locking up/crashing because it is trying to load too many events at one time.

**Comment by charlag** [comment]
Can you please disable some of the calendars in the side menu (by pressing the square next to the calendar name)? Does it change anything?

**Comment by charlag** [comment]
Unfortunately I was not able to reproduce it so far. I am wondering if there's some very old event which we have to calculate or some special condition for the event. I tried to create couple of daily events but they all worked correctly. It might be time zone related or something similar. Any hints are appreciated.

**Comment by marissarousseau** [comment]
So I noticed that the lag seems to happen as I scroll through months that have repeating events. So if I have 0 repeating events for the month of July, August, and September it's fine, but as soon as I start to scroll past October, where I have a weekly repeating event on each weekday (Mon - Fri) that repeats forever, the lag starts to occur, when scrolling through those months. When I enable my calendar which has **several** weekly events on each day of the week, the lag is even worse, generally causing the app to lock up. Once the "app not responding" message comes up, if I tap "Wait" instead of "Close app", the app eventually stops freezing and allows me to switch to the next month. But as soon as I try to switch to the month after that, the same thing happens.

**Comment by charlag** [comment]
@marissarousseau can you confirm it still occurs?

**Comment by marissarousseau** [comment]
@charlag yes it still happens to me on the most version of the Android app. I have to use the Agenda view to be able to see everything without the lag.

**Comment by marissarousseau** [comment]
Just confirming again that this issue occurs on the latest version of Tutanota on Android.  I'm including a [screen recording](https://imgur.com/VJSYXzu) for reference. There is very noticeable stuttering and lag when switching between months in the month view.

**Comment by MarissaRS** [comment]
This issue seems to have gone away in recent updates.

**Comment by charlag** [comment]
@MarissaRS great, thanks for letting us know
