### ISSUE TITLE
Why does tutanota desktop client uses so much RAM?

### ISSUE THREAD

**Issue by Gaspacchio** [tutao/tutanota#2127]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Not exactly a bug, more a concern about the amount of RAM used by the desktop client. Idling, the desktop client uses around 120 Mb of RAM on my computer, that's a fair amount to me.

**To Reproduce**
1. Launch the desktop client

**Expected behavior**
The desktop client should be more memory efficient.

**Screenshots**
![image](https://user-images.githubusercontent.com/43613824/86150147-4710d880-bafd-11ea-8a3c-1ddce3820c73.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.330
 - ~~Desktop Environment, if applicable (on Linux)~~
 - Version 3.74.2

**Additional context**
I am well aware that this is not really a bug, but as no issue was open I thought that it would be interesting to start tracking the evolution of memory usage of the Desktop client to improve it over time rather than degrade it.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

About your question: because it's Electron. It's the same code as mobile apps and there are no big problems with memory there.
