### ISSUE TITLE
Please reconsider allowing us to use existing mail clients

### ISSUE THREAD

**Issue by r-giskard-reventlov** [tutao/tutanota#2136]
Would it not make more sense to adapt existing/create protocols to allow users to benefit from integration with their current stack, whilst at the same time being more secure. The current approach feels more like a walled garden.

I have to support and use two desktop apps, one (Evolution) which integrates completely with the rest of my stack, which connects to multiple email accounts/calendars/rss feeds, and Tutanota. In my use case, which I'm sure is shared by a large percentage of users, the ability to 100% ensure the confidentiality of my emails while stored on my desktop comes second to being able to work efficiently.

We've gone (generally speaking now) from a place where open protocols allowed us to choose which client we used, letting **users decide** which features were import to them, to a "trust us" approach where we only get the features **XYZ company think will benefit users whilst at the same time keeping them in your garden**. These two criteria are all to often mutually exclusive.

I'm sure there are some technical reasons why we can't use existing protocols (perhaps I'm even wrong on this) but surely it's up to the user to decide how they interact with the service? Surely some time can be put into adapting/creating protocols so that we can make use of your service (which I have to say is generally exceptional) while at the same time making use of other services through integration?

**Comment by AFulgens** [comment]
I have to agree here. It is all well from an incentive point of view to build something, which is perfectly contained in a web-setting. But at the same time not leveraging an expert-option for integration with software like Thunderbird (which would solve a lot of problems, like archiving, see Issue #1440 ) feels a bit... silly?

I know that it is a different world-view, because you provide a self-contained, e2e encrypted enclosure for e-mails, and as more and more people use Tutanota, you can e2e encrypt more and more. But let's be honest, UX-wise you are at a disadvantage, just because you are younger (crucial features like folder nesting #927, e-mail import #630, or sender name for aliases #516 are still at large and missing, and it's because you have limited manpower + resources and cannot focus on just UX, when you have totally different mission priorities with privacy).

**Comment by mpfau** [comment]
We definitely will support open protocols that are secure and easy to use. The problem is that there is none at the moment. And we are definitely not in a position to define and standardize new protocols at the moment.

Coming up with a new protocol makes no sense unless important players (e.g. Thunderbird, Outlook) are involved and agree to implement that protocol. I don't see any interest from those parties and that is why we fully focus on our own clients.

Which features are crucial is a very subjective question. However, we are substantially growing our team and will continue to increase velocity.

**Comment by r-giskard-reventlov** [comment]
I'm not sure that you have to try and standardise the new protocol @mpfau, or to your point on major player, have agreement/investment. I think it's a case of having some means of interacting with your mail servers (which you already have as it's supported for your official desktop client) and letting the open source community fill in the blanks, which I'm certain they will. The crucial point I guess is that you don't require a standard, just a means by which to achieve this.

I'd really love to stop the proliferation of apps which do almost the same thing, however I wont push this any further as I'm sure I've made my point.

Again, thanks for the service as it really is top notch :-)

**Comment by charlag** [comment]
@r-giskard-reventlov not sure what you would like us to do. API is there (even though we can't provide stability guarantees yet) and anyone is free to add their own bridge/client, we don't have any secret app token by which we filter out the app and I think if you looked around you would find previous attempts to do so.

**Comment by spartanz51** [comment]
> We definitely will support open protocols that are secure and easy to use. The problem is that there is none at the moment. And we are definitely not in a position to define and standardize new protocols at the moment.

We should manage ourself what we think is safe or not regarding our usage.
Mail integration is a priority feature for a majority since years

Btw, why do you want a secure protocol when you're about to implement a backdoor for a gov?
