### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gohanko** [tutao/tutanota#2163]
Hi!

Looking through the code, I can't seem to find the server code for handling emails and such. Is it only the frontend apps that is open sourced?

Regards,
Brandon

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests or questions here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

Source code for the server is not available.
