### ISSUE TITLE
No email notification for received emails for contact form users

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2180]
We need to check if the same is also true for non contact form users.

How to reproduce:
1. Send a contact form request and enter an external email address for notifications.
2. Reply to the request
-> No notification email is sent.

We use the contact form user email address as sender which has a whitelabel domain address. Whitelabel domains are usually not allowed to send emails.

**Comment by johnbotris** [comment]
I can reproduce this inconsistently at best on my dev system.

It seems that when the external user mailbox is logged in at the time of sending a reply, or if a notification has already been sent for a given email, then no notification is sent. Is that the intended behaviour?

**Comment by hahub** [comment]
This is connected to the TXT records of the custom domain. For now, please follow these instructions to make sure notifications are being received: https://tutanota.com/howto#settings-forms

"The people making contact form requests on your website will have the option to provide their own private email address to which they will receive a notification when you respond, informing them that there is a message in their secure mailbox. To ensure that these notifications can be sent, make a TXT Record in the DNS settings for your whitelabel domain, with the value "v=spf1 include:spf.tutanota.de -all". They will still be able to communicate securely without this, but the notifications may not be received."

**Comment by vaf-hub** [comment]
I think this is related to  #2577. I also had trouble to reproduce it reliably, but started working on a solution on the server-side. @johnbotris if there is either an open websocket connection or if a notification mail has already been sent but nobody has  logged into the mailbox since, then no further notification mail is sent. So this seems to be the intended behavior.

**Comment by vaf-hub** [comment]
We already explain that at least an spf TXT record has to be set so that the mails sent from the whitelabel domain do not get delivered to spam. We should include this info in the client or at least point to the how-to: https://tutanota.com/howto#settings-forms

**Comment by bedhub** [comment]
Setting the spf TXT record is not necessary. It is already present because we have the CNAME record pointing to login.tutanota.com and there the spf entry is defined. What is missing is dkim, dmarc and mta-sts records because they are on other subdomains.

Notification to other addresses are only sent for the first email that arrives after the user logged out. The logged in state is currently tracked by the websocket connection. As long as the websocket connection is active no notification emails will be sent.
