### ISSUE TITLE
Links to faq do not respect language

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#2183]
All links from Tutanota (e.g. support/settings dialog) should lead to the correct language for the user.

As we don't have exactly the same language set for website and Tutanota, this should be implemented as follows:
* Add handling for an additional parameter to the website (e.g. `?autolang`). If this parameter is passed, switch to the language based on browser preference.
* Change all links from Tutanota to the website to include the `autolang` parameter.

**Comment by vaf-hub** [comment]
After a discussion with mpfau we decided
1. not to introduce the `?autolang` parameter (because the links do not look nice and we always have to remember to include it),
2. to change the website such that it shows all pages based on browser language (or stored preferences from localStorage) and
3. to provide just one generic version for all links (currently there exist at least two versions for several links in the client) and let the website handle languages as explained in 2.

**Comment by vaf-hub** [comment]
The changes to the website were just published in commit 0941e7aa.
