### ISSUE TITLE
Calendar import might fail because of the duplicate UID

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2220]
It should already be de-duplicated, we should find out how it happens.

```
Client: Browser
Tutanota version: 3.76.6
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
PreconditionFailedError
Error message: 412: db.exists | POST /rest/tutanota/calendarevent/MFEQIxP--B-2
Stacktrace:
PreconditionFailedError. 412: db.exists | POST /rest/tutanota/calendarevent/MFEQIxP--B-2
PreconditionFailedError@https://mail.tutanota.com/common.js:1:255279
@https://mail.tutanota.com/common.js:1:250748
value/
```

**Comment by bedhub** [comment]
Happens when importing calendar with with two events which have the same uid. Example:



BEGIN:VCALENDAR
PRODID:-//Tutao GmbH//Tutanota 3.76.6//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART:20200929T120000Z
DTEND:20200929T123000Z
DTSTAMP:20200929T122010Z
UID:LmxvOeF----01601381999855@tutanota.com
SEQUENCE:2
SUMMARY:test 1
ORGANIZER;CN=bedfortest at TEST;EMAIL=bedfortest@tutanota.de:mailto:bedfortest@tutanota.de
END:VEVENT

PRODID:-//Tutao GmbH//Tutanota 3.76.6//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART:20200929T120000Z
DTEND:20200929T123000Z
DTSTAMP:20200929T122010Z
UID:LmxvOeF----01601381999855@tutanota.com
SEQUENCE:2
SUMMARY:test 2
ORGANIZER;CN=bedfortest at TEST;EMAIL=bedfortest@tutanota.de:mailto:bedfortest@tutanota.de
END:VEVENT

END:VCALENDAR

**Comment by bedhub** [comment]
And here the stack trace from the server for the duplicate uid. Both cases (#2324, #2220) are ending up in the same client error (Precondition failed with db.exists). We need to distinguish them because we need to handle those cases differently.

```
I 09:02:35.526 sys RootHandler.java:327 Llp-DKR----1 Cannot create same uid index twice - POST /rest/tutanota/calendarevent/Llp-yIK--7-1/ 
de.tutao.tutadb.rest.exceptions.PreconditionFailedException: Cannot create same uid index twice
```
