### ISSUE TITLE
make a tutanota client port for kaios 

### ISSUE THREAD

**Issue by epicodertime** [tutao/tutanota#2236]
Tutanota should make a client for kai os as the user base  is growing pretty fast and it would be nice to have a client for it.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

KaiOS just uses old Firefox as an engine so web should work absolutely fine there. If anyone is interested in packaging it for KaiOS, godspeed.

**Comment by epicodertime** [comment]
@charlag i made a client for kaios should i make a pull request for it?
[tutanota-kaios-client.zip](https://github.com/tutao/tutanota/files/5175904/tutanota-kaios-client.zip)
