### ISSUE TITLE
DropdownSelectorN onClick called when clicking on the helpLabel

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2238]
The helpLabel itself can contain interactive elements like links, so clicking it shouldn't open the dropdown.

**Comment by johnbotris** [comment]
currently `helpLabel` on `DropDownSelectorN` is just a `lazy<string>` If we change it to `lazy<Children>` and then pass it an <a> for example, the link will be followed instead of activating the dropdown. Having the dropdown activate when the label or helpLabel are clicked is useful for mobile anyway.

**Comment by charlag** [comment]
It's a problem if there's a link/button in a help label (like for new desktop client button to check for updates)
