### ISSUE TITLE
Improve window management

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2244]
- Change option "Run as tray icon" to "Run in background" add help label with link to FAQ
- Remove shutdown button
- Linux analyse quit button in activity menu if we can quit the whole application
- Use notification overlay to display that a new version is available with restart option.
- On mac support Cmd + N shortcut to open a new window when no window is visible

**Comment by cari73** [comment]
![Uploading 92548056...]

**Comment by cari73** [comment]
![image](https://user-images.githubusercontent.com/69138620/92548056-aedd5100-f21b-11ea-8d01-b73528b9c462.jpeg) you

**Comment by ganthern** [comment]
For GNOME, there seems to be no (easy) way for electron to quit the app when the application menu "quit" button is pressed.

Afaict, the application menu is calling request_quit() on the app:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/panel.js#L107

I'm not sure it's identical, but the call may be forwarded to shell_app_request_quit(), which closes all the app's windows unless the app explicitly exports a quit action to call:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-app.c#L1201

Since we don't want to quit the app just because all windows are closed (the tray should stay open), and we can't tell apart this close event from e.g. the window's top bar 'x' button, this will stay confusing until GNOME inevitably removes the application menu completely.

**Comment by bedhub** [comment]
- [ ] Run in background mode disabled: check that application is closed when last window is closed (Windows, Linux, Not on Mac)
- [ ] Run in background mode disabled: check that application is still running when the last window is closed (Application can be closed using tray icon/task bar/ or menu bar on macOS)
- [ ] Shortcut Cmd +N should open a new window when all windows are closed.
- [ ] Check that context menus are still working 
- [ ] Check that link to faq entry for Desktop setting "Run in background" is present
- [ ] Check that info banner is shown when an update is available

**Comment by ganthern** [comment]
> Test notes:
>     * [ ]  Shortcut Cmd +N should open a new window when all windows are closed.

This is for mac, make sure to have Tutanota Desktop active in the global application menu (not Finder or something else) when testing this. Also test that Cmd+N _doesn't_ open a new window if something else is active.
