### ISSUE TITLE
small event popup in calendar persists across tabs

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2552]
1. Switch to tab "Calendar", (if necessary create an event) and click on the event
2. a small "popup" will open
3. now press any shortcut to switch View (such as **S** for settings)
4. the popup will persist to the next tab, and also allow for the editor to be opened and the event to be deleted

expected behavior: popup should close when switching tabs, or no shortcuts allowed when popup is open

**Comment by jowlo** [comment]
Adding shortcuts in #2557 will automatically deactivate the general view shortcuts while a Modal is visible. We only check if more than one shortcut (help is always there) is registered for the modal, otherwise the general shortcuts are active, see https://github.com/tutao/tutanota/blob/51a0e809b1194a96fe75b53704c09c028977b6c9/src/misc/KeyManager.js#L116
