### ISSUE TITLE
Add the ability to import emails from MBOX format.

### ISSUE THREAD

**Issue by cnighswonger** [tutao/tutanota#2629]
This should be as trivial as adapting the mail draft code to handle the import.

**Comment by cnighswonger** [comment]
Would this feature be better:

1. Integrated into the mail client... or...
2. As a stand-alone crosswalk application?

Note: If this should be discussed elsewhere, feel free to point me in that direction.

**Comment by charlag** [comment]
Currently there's no import, I think we should come back to this once we have it. I think MBOX is simple enough that it can be in the app.

**Comment by cnighswonger** [comment]
Wow!

It is clear that Tutanota has zero intentions of running an open source project.

Sorry to waste your time. we'll take our resources elsewhere.

**Comment by charlag** [comment]
It's not possible to implement import at the moment, I just meant that

**Comment by castarco** [comment]
I don't think that the current impossibility is a solid reason to close a legit issue, it only justifies saying that it will take long until someone can jump into it.

A better reason would have been that the feature request was not clear or specific enough.

As a user of Tuta, I feel quite discouraged when I see these responses almost every single time I have a problem and I come here to see if anyone else has gone through it too (it's usually the case, and it's also usually the case that they are closed "just because").
