### ISSUE TITLE
Provide enterprise installation for Windows desktop client

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2730]
* Silent installation, so it can be automatically distributed to machines
* Installation for the machine, not just the user
* No automatic update

#2736 should also be fixed for this enterprise installation

**Comment by ganthern** [comment]
Assuming this is only for windows: silent installation for all users (in C:\Programme) can be done now when running the installer as admin with

`.\tutanota-desktop-win.exe /S /allusers`

disabling updates could be done with dist `--custom-desktop-release`, but that one builds for the current platform.

see (https://github.com/electron-userland/electron-builder/issues/4445)

**Comment by ganthern** [comment]
see also: https://gitlab.ow2.org/RocketChat/Rocket.Chat.Electron/-/blob/master/build/installer.nsh

**Comment by mpfau** [comment]
The desktop client can be installed on windows in "enterprise mode" by passing the following flags to the installer:

/S - Install silently (no wizard)
/allusers - Install for all users on the system rather than just the current user (requires privilege escalation)
/disableAutoUpdates - Disable automatic updates (updates would need to be done manually by an admin)

The application may also be uninstalled silently, by passing /S to the uninstaller (found in the installation directory under Program Files)

**Comment by mpfau** [comment]
test notes:
- [ ] uninstall and run silent install, run desktop client from terminal: Update check should be enabled
- [ ] uninstall and run silent install with /disableAutoUpdates, run desktop client from terminal: Update check should be disabled
