### ISSUE TITLE
this._contactList is undefined

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2856]
v3.82.8

Seems like in some places in ContactView we assume it's there while in others we check. It likely happens there.

**Comment by vaf-hub** [comment]
I created a commit to check in all places whether _contactList is defined before accessing it.
However, I am not sure in which cases it can be undefined so that I can reproduce the error.

Initially updateUrl() is called twice. First  the URL is reset based on what we get from the contactModel and then again to set _contactList with the id we got in the first call. Not sure in which case we would not find such a list id and what other consequences this has.

**Comment by charlag** [comment]
List ID would not match if it's passed by user and not set by us.
E.g., if you open the contacts view, the reload the page but login with another account.
I think if it *can* be `null` then we should make the field itself nullable.

In genegal I don't like the whole mess. Maybe it should be a wrapper for another component which has proper contact list for sure but this would be a bigger refactoring.

**Comment by vaf-hub** [comment]
OK, that makes sense. I updated the commit and made the field nullable. However, we check for null in a lot of places now. I don't think I want to create a wrapper component now just because _contactList can be null. Maybe we could also think about how to handle such incorrect list ids passed in the URL in order to ensure that _contactList is always defined.

**Comment by charlag** [comment]
As we load contact list async we would need to delay construction of ContactView and it's not easdy to pull off right now

**Comment by vaf-hub** [comment]
I see. Should we then include my fix for now and open another issue to improve the handling of undefined ContactView in _contactList?

**Comment by charlag** [comment]
Would be easier if you opened PR, I have some comments I think (like `headerView()`)
