### ISSUE TITLE
Include dot at the end of a CNAME record value

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2877]
Some domain providers require a dot at the end of a CNAME record value. If the user then does not add it the domain itself would be added to the value.

Example for example.com:
| Type | Host/Domain | Value          |
| ------ | ------------------ | --------------- |
| CNAME |  s1._domainkey |  s1._domainkey.tutanota.com |

Would extend to the value **s1._domainkey.tutanota.com.example.com**

We just have to add the dot at the end in the add domain dialog.

| Type | Host/Domain | Value          |
| ------ | ------------------ | --------------- |
| CNAME |  s1._domainkey |  **s1._domainkey.tutanota.com.** |

**Comment by vaf-hub** [comment]
The final dot for CNAME records will be added on the server, because we need to change the DNS record check on the server for the final dot anyway.

This can be closed as soon as `final-dot-cname` is merged on the server.

Test-notes:

- [ ] setting up custom domains with the values given in the AddDomainWizard still works fine.
- [ ] custom domains that are setup with the old values are still shown as correctly configured.

**Comment by charlag** [comment]
We should track this on the server then

**Comment by vaf-hub** [comment]
@jowlo and I discussed this again and decided to make the change in the client after all. I reopen it.
