### ISSUE TITLE
Improve loading time of worker

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3165]
- Use dynamic imports in worker to load it faster. This is one of the main slowdowns on login as worker is a big chunk and we probably don't need all the indexer things to log in.
- For development we compile to ES6. Dynamic imports are currently not supported in Firefox ~~or Safari~~ supported since Safari 15, Firefox in development. 
- Another idea: Create separate worker thread for search index

## Test notes
 - [ ] Test all platforms
   - [ ] android app
   - [ ] ios app
   - [ ] desktop app
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Chrome on Android
   - [ ] Firefox on Android
   - [ ] Safari desktop
   - [ ] Safari ios

**Comment by charlag** [comment]
Firefox *finally* merged ES modules in the worker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

we  should wait some time and start using them

**Comment by charlag** [comment]
It seems like putting search into it's own chunk does not do much for the loading time of the worker (on moto 5G the worker startup time is about 450ms, empty worker startup time is around 50ms). We might get better results if we import most things dynamically already.

We should start using dynamic imports in the worker, it doesn't matter for debug builds (because esbuild) and doesn't matter for dist builds (because systemjs)
