### ISSUE TITLE
Opening emails on mobile is still janky

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3222]
v3.84.7

 * We still render mail body too early, just before animation is actually done. This loses some frames on some emails
 * We flash progress indicator for a split second which is hard on eyes (seems to be # #3120 but is a bit different case)

**Comment by everydayanchovies** [comment]
Is it acceptable if I program a switch to disable animations? I could see the added code complexity being seen as unnecessary overhead. (if animate x else y). 

I'm personally slightly annoyed each time I open an email on my phone due to the animations. They are laggy but also linear which makes them come off feeling weird. 

In either case, I could look into this. Best case scenario I could hook into an event that is triggered when the animation is finished. But if that proves impossible, is it acceptable to wait x milliseconds before rendering?

Cheers,

Max

**Comment by charlag** [comment]
@everydayanchovies do you talk about all animations or the issue?
I don't think we want to disable them without strong reason. If you experience issues, we should fix them rather than disabling them.

**Comment by everydayanchovies** [comment]
@charlag just the animation for opening an email (slide in from the side).

**Comment by charlag** [comment]
@everydayanchovies we just need to work on it, yes. We need to re-do it completely IMO

**Comment by everydayanchovies** [comment]
I had a look at the code and read up on relevant things, is this not something to read into? Specifically requestAnimationFrame.

https://developer.mozilla.org/en-US/docs/Web/Performance/CSS_JavaScript_animation_performance

**Comment by charlag** [comment]
This was fixed while working on #3746 
Some bugs were uncovered
