### ISSUE TITLE
Running make between test invocations does not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3233]
```sh
$ npm test
$ node make
$ npm test # will fail
```

This happens because make will clean the folder initially and test does not write some bootstrap files each time.

We should either not clean the whole build directory on make or write files each time for test.

Workaround for now is to invoke test with -c like
```sh
$ cd test
$ node test client -c # or
$ node test api -c
```

**Comment by johnbotris** [comment]
It seems like the problem is that if you run `node make` without any `BuildServer` running, then it will start up a new one using `Builder.js`. If I then run `node test`, it will use the existing `BuildServer` which will then use the same builder from `make`, and not switch to `TestBuilder.js`. If you run either `test` or `make` with `-c` then it will reset and start using the correct builder

**Comment by charlag** [comment]
make might delete test-index.html and it won't be generated with the next test invocation.

Easy solution would be to generate all files each time for tests.

The right solution would probably be:
- separate the build folders
- Separate build servers
