### ISSUE TITLE
Improve layout in ContactFormView

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3246]
There is no padding or margin between the top of the header text and the page header, and the header/footer text both extend out much further to the left than the buttons. This might have come after the UI refactoring?

![Screenshot from 2021-07-05 17-10-31](https://user-images.githubusercontent.com/22109738/124491786-f12bdc00-ddb3-11eb-802f-fe9cb6278404.png)

**Comment by ganthern** [comment]
Alignment is borked on new contact forms with rich text blocks:

<details>
  <summary>screenshots</summary>
  
![image](https://user-images.githubusercontent.com/29049728/126623746-4be17933-e1ae-4bdc-816c-d137b40eeca7.png)
![image](https://user-images.githubusercontent.com/29049728/126623503-0d94555f-8334-4ab2-bfed-3d8aa987ad43.png)

</details>

This fixes itself after setting the alignment to centered and back (see header text):

<details>
  <summary>screenshot</summary>
  
![image](https://user-images.githubusercontent.com/29049728/126624036-0e92a225-7668-4679-9b2f-0285abad45e4.png)

</details>

Seems the second part of this issue is not addressed by the commit.

**Comment by vitoreiji** [comment]
Discussing with @bedhub we decided that the left alignment is not really a problem, since the user can align to the center if they want.
