### ISSUE TITLE
Accounts disabled 

### ISSUE THREAD

**Issue by xo10** [tutao/tutanota#330]
**I've two email accounts from tutanota service and all of my accounts are disabled?

Anyone report to any account from tutanota service without proof by just click your email as spam and your email will be closed directly!!!

Feeling upset from the service, I can't trust from this company anymore.

Already my email has been sent to:
hello@tutao.de**

**Comment by mpfau** [comment]
Thanks for your feedback and sorry for this inconvenient experience! We always do our best to treat real users as good as possible and to only close spammers accounts in order to protect all of our other users from them. However, as all mails are only stored encrypted, failures happen from time to time.

I just checked our hello@tutao.de inbox and couldn't find your request. Please send it again. Thanks!

**Comment by xo10** [comment]
already sent it
![1](https://user-images.githubusercontent.com/35911698/38163604-8619ab5a-34ff-11e8-9abc-8a1b4a1e1266.png)

**Comment by xo10** [comment]
+

How do you know if the account is spam or not?

I believe that the email is encrypted and anyone can spam to any tutanota account ( easy to close any account as what happened to me (2 of them so far)

Proof, please?
