### ISSUE TITLE
Three digit colors in whitelabel theme causes crash/error in apps 

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3303]
We didn't release 3.83.5 for iOS because there were some bigger issues that need fixing, relating to https://github.com/tutao/tutanota/issues/2804. We should fix them and then make a 3.85.3 iOS release, or do it with the next release

Update: This is due to 3 digit hex color codes not being handled in the native part, and also happens in android

---

# testing
Test in
- [x] desktop
- [x] ios
- [x] android

* in whitelabel color config, set `header_bg` and `content_bg` to three digit hex codes
- [x] The colors are rendered correctly and the app doesn't crash when using custom color theme in clients
- [x] Six digit color codes also still work
- [x] Android light colors are detected correctly and native backgrounds/status bars etc are updated accordingly 
- [x] #3312

**Comment by bedhub** [comment]
App do not crash anymore but:

- [ ] status bar on android does adapt to the color header_bg or content_bg
- [ ] status bar on ios device does change when changing content_bg, is this intended to be like that? I think the status bar should pick up the color of header_bg
- [ ] When in light/blue the font in the status bar is not readable because it is also white.

**Comment by vitoreiji** [comment]
> status bar on android does not adapt to the color header_bg or content_bg

It does adapt to `header_bg` for me on Android 7.1.2:

![adapted_statusbar_android](https://user-images.githubusercontent.com/197261/126761808-86fa9202-4360-4315-b460-8806579d2c3c.png)
