### ISSUE TITLE
Timeout when uploading attachments

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3308]
People are still getting connection timeout errors when uploading attachments and then a "Looks like you are offline" message appears. It is happening for larger (> 20MB) and also smaller (< 5MB) attachments.

In issue #406 we said it is a browser bug and therefore we closed it but this case is from the Windows desktop client and it could be a different case.

In the particular case when we upload the attachment we can also try to catch the error and say "Failed to upload attachment, connection timed out." instead of showing an offline message which is wrong in this case because the user is online.

Example Stacktrace
> 2021-07-16T02:10:26.814Z I "error",ConnectionError
>  Error message: Reached timeout of 20000ms  | PUT /rest/tutanota/filedataservice
> Stacktrace: 
> ConnectionError: Reached timeout of 20000ms  | PUT /rest/tutanota/filedataservice
>     at XMLHttpRequest.d.onabort (file:///C:/Users/tk4/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/worker.js:1:101340)
>     at abortFunction (file:///C:/Users/tk4/AppData/Local/Programs/Tutanota%20Desktop/resources/app.asar/worker.js:1:99493)

Client: win32
Type: PREMIUM
Tutanota version: 3.84.11
Timestamp (UTC): Fri, 16 Jul 2021 02:10:54 GMT

**Comment by charlag** [comment]
@bedhub did you have any more cases like this?

**Comment by CyberScooby** [comment]
I encounter this issue on the Windows Desktop client for even tiny attachments. It makes sending even a small picture extremely difficult as I have to disconnect from my VPN protection and keep hitting send until it finally works. Often takes many tries and could mean asking everyone to stop using internet for a bit.

I live in a rural area so we don't get a choice of internet speeds. We get 800k up and that is it. Well rated for 800k but of course we never hit that. Is there some setting I can use to adjust the timeout period?

I have had this issue since day 1 - when I started using Tutanota, sometime last year.

I should be on the latest client as it just upgraded less than a week ago. I will update this post with version info after I get this email to send.

**Comment by CyberScooby** [comment]
Tutanota 3.100.0
Windows 10 Enterprise - 20H2
Ethernet cable (wifi disabled)
Lenovo laptop with docking station - powered, NOT running off battery

Trying to send a zip file of some text files. Entire thing is about 662 kb and it fails every time. Tells me I am offline about about 20 seconds. Been trying off and on for days. Even today wouldn't work when my entire family was gone, so my laptop and my smartphone are literally the only devices using the internet connection. I keep everything else unplugged to stop using phantom power in their "off" state. 

Uploading attachments has always been extremely challenging. I am assuming it is my slower rural internet connection.

Been putting up with it thus far but starting to send more attachments ... at least I am trying to.

**Comment by charlag** [comment]
@CyberScooby is this with desktop app or in a browser? W time out when we see no progress for 20 seconds

**Comment by CyberScooby** [comment]
@charlag That was strange. I logged into my account in Firefox and found that my draft message was saved in my account, along with the attachment. So I went into Edit mode and hit send. It went out in a very short amount of time.

Just tried the same test with a new email on my desktop app and it worked like a charm. First time ever. The app did update earlier today so maybe the issue is already fixed. Will run some more tests (hopefully tomorrow) and see if I was just lucky or not.

**Comment by CyberScooby** [comment]
- I have done additional testing with a 3.9 MB PDF and am receiving the same results
- It also failed to save a draft - same message stating that I am offline, even though the top bar on the Windows app clearly states online & everything else internet based works fine
- Just upgraded to 3.102.3 with the same results

To me it seems like you have a builtin timeout that is not account for people who only have access to slow connections

FYI - I did this testing with my VPN turned off

**Comment by CyberScooby** [comment]
I just upgraded to 3.105.4 (Windows desktop) & ran some more tests. As before, I used a wired internet connection with the VPN turned off.

50.6 KB webp - worked on first attempt
926.8 kb pptx - worked on first attempt

1.3MB exe - worked on third attempt

2.1 MB pptx - no luck after three attempts
3.8 MB PDF - no luck after three attempts

**Comment by mpfau** [comment]
@CyberScooby so this does not happen on browsers (Firefox/chromium) but only on the desktop client?

**Comment by CyberScooby** [comment]
I've never actually used the browser as the desktop app is probably more secure. To be honest I completely forgot about that option.

Just gave it a try (Firefox) with a 2.2 MB file and it worked fine. So at least I have a workaround now. Thanks!

**Comment by CyberScooby** [comment]
Recently I have had to send a variety of attachments with your Windows application, version 3.114.1. It seems that this bug has been fixed as I had no issues, other than having to wait for my slow internet to upload the attachments, which of course has nothing to do with Tutanota.

I have even signed up for a paid account now that I am using it more regularly.  :)

**Comment by mpfau** [comment]
@CyberScooby Thanks for reporting back. Glad to hear!
