### ISSUE TITLE
Each update clears the color theme setting

### ISSUE THREAD

**Issue by mscofield0** [tutao/tutanota#3316]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Tutanota on Windows clears the color theme setting on each update as of late.

**To Reproduce**
Just update Tutanota.

**Expected behavior**
The color theme should persist between updates.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by charlag** [comment]
@mscofield0 hi, thanks for reporting. Do other things e.g. saved logins or search index disappear as well?

**Comment by mscofield0** [comment]
I don't know about search indexes disappearing (I don't use the feature often), but logins were kept intact.

**Comment by mscofield0** [comment]
Ah, no, not anymore. It seems to have stopped. Closing the issue.

**Comment by mscofield0** [comment]
Just happened again on Windows. Version v3.87.1

**Comment by johnbotris** [comment]
I've found another case where the color theme (inconsistently) gets overwritten, and that's when doing mailto handling. It seems like sometimes we are writing to the desktop config file but the selected theme hasn't been set on the native side.

I would guess it's due to the fact that we are starting up new instances of the app to do the update as well as to handle mailto, so perhaps something is not being handled properly there.

**Comment by ganthern** [comment]
Testing: see https://github.com/tutao/tutanota/issues/3628

**Comment by mscofield0** [comment]
Happened again after updating to v3.89.12 on Windows 10.

**Comment by johnbotris** [comment]
The problem has been fixed with 3.89.12, so it should no longer happen with future updates
