### ISSUE TITLE
Bad formatting in calendar event invitation description sent from Microsoft Teams

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3507]
Invitations sent from Microsoft Teams to Tutanota do not have  line breaks in the description and have an additional backslash before each comma. In Tutanota it shows up as e.g. "Hello\,This is the invitation\,Cheers\,Alice"

However, the corresponding ics file has "\n" for line breaks, e.g. "DESCRIPTION;LANGUAGE=en-US:Hello\,\n\nThis is the invitation\,\n\nCheers\,\nAlice"

This is at least the case for invitations sent from Microsoft Teams, might be the same for other Microsoft products.

**Comment by johnbotris** [comment]
This is a general problem with invitations coming from Outlook (so I guess teams as well) where they send out .ics files that have plaintext in the description rather than HTML, this was the root cause of this issue: https://github.com/tutao/tutanota/issues/2741

Do the problematic .ics files have any indication of their format? We might otherwise have to try to detect what format the description is in.

**Comment by armhub** [comment]
I do not see any indicator of a format. It looks like it is not even limited to Microsoft. I found those two cases for the "PRODID" property in ics files that have this formatting issue:
PRODID:Microsoft Exchange Server 2010
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN

So I guess we have to detect it ourselves.

**Comment by charlag** [comment]
It's generally inconsistent between calendars. Google Calendar and Apple Calendar also don't agree on HTML/plain

**Comment by murilopereirame** [comment]
See https://github.com/tutao/tutanota/issues/4685#issuecomment-1855541373
