### ISSUE TITLE
Update to Electron 15

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3657]

**Comment by charlag** [comment]
I dived into the depths of Chromium and it indeed might be /tmp but I think it's `/tmp/tutanota` or `/tmp/tutanota_test` for us

**Comment by vaf-hub** [comment]
> 

Yes I think so too. However, I am not sure when this directory is created in the first place (at least on Linux). I could not find this directory at any point. Are you sure it is created on Linux at all? And if so how can I trigger the creation?

By the way I found a comment in the code saying that tutanota_desktop_lockfile is written to the root temp directory on purpose so that it persists.

**Comment by charlag** [comment]
@vaf-hub it is created once you "open" the attachment I think, probably also when just downloading attachments

**Comment by vaf-hub** [comment]
In fact I always tried to download attachments and that does NOT create the temp directory. I now opened it directly from the desktop client instead and that does create the directory. So, I was finally able to confirm that it is removed after closing the app.
