### ISSUE TITLE
Importing event with same start and end time is considered as multi day event.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3764]
When importing the attached event Tutanota shows a two day event although start and end date are the same and it should just be an all day event. Start and end time are the same.

DTSTART:20220204T050000Z
DTEND:20220204T050000Z

[event.txt](https://github.com/tutao/tutanota/files/7829299/event.txt)

![Screenshot from 2022-01-07 15-12-29](https://user-images.githubusercontent.com/8296817/148556661-78fa03bb-59de-44fb-831c-d4947ae8e997.png)

**Comment by charlag** [comment]
@bedhub my guess is that this is not valid by the spec and we just pick some duration

**Comment by vaf-hub** [comment]
In the [spec](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.2.2) it says: 

> The value type of this property MUST be the same as the "DTSTART" property, and its value MUST be later in time than the value of the "DTSTART" property.

Therefore we should decide what to do when importing such an event. I propose we convert it to an all day event on the same day.

**Comment by ganthern** [comment]
Events of this form technically have a startTime and I think we should try to honor it to make sure reminders are fired at the right time.

I'd try to prevent the following:
* create a "reminder" style event for this evening without a duration in some calendar software that exports those as zero-length events and export it (imagine a reminder like "I have to take these pills at 1800"
* import that event in tutanota at 1700, which creates an all-day event _for this day_
* never get an alarm because the event already started

Solutions:
* convert the event to have a duration of 1 minute, 5 minutes or 1 hour or run to end-of-day
* show a warning that an event was fixed like this
* don't import events that have errors like this

**Comment by ganthern** [comment]
## Testing
some illegal ical events:

[allday-export.txt](https://github.com/tutao/tutanota/files/8283773/allday-export.txt)
[illegal-allday.txt](https://github.com/tutao/tutanota/files/8283774/illegal-allday.txt)
[illegal-event.txt](https://github.com/tutao/tutanota/files/8283775/illegal-event.txt)

### Importing events
* [ ] importing events with endTime <= startTime works and displays as a zero-duration event that starts at startTime of the import
* [ ] importing all-day event with endTime <= startTime works and displays as an all-day event with a duration of one day
* [ ] re-exporting illegal events works as expected

### Regressions
* [ ] importing normal events works
* [ ] importing multi-day events works
* [ ] importing all-day events works
* [ ] importing events with impossible times or syntax errors gets rejected
