### ISSUE TITLE
Post-typescript task: stricter types

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3780]
We should make use of stricter type checking e.g. field visibility and field initialization.

## Test notes
 - [ ] Buttons
 - [ ] Dropdowns
 - [ ] Recipient fields
 - [ ] Mail viewer works
 - [ ] Whitelabel settings are shown

**Comment by vitoreiji** [comment]
Would it make sense to first revisit all `@ts-ignore` and `as unknown` usages in the code?

**Comment by charlag** [comment]
@vitoreiji `unknown` is actually okay, `any` should be limited though. I pretty much went through all `@ts-ignore` in the main code already while finishing the conversion.

**Comment by vitoreiji** [comment]
Yeah, I saw that you had done that, so that's why I deleted my comment.

I had added some `thing as unknown as Whatever` in some places to quickfix some errors, and I don't think we should keep those. If we decide to keep the casting, than I would prefer to use `downcast<Whatever>(thing)` to be more explicit.

**Comment by charlag** [comment]
@vitoreiji yeah we should probably check that as well
