### ISSUE TITLE
Build server: build after clean build also rebuilds

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3841]
Example with tutanota project:

1. node `make -c` restarts build server
2. running `node make` again will also restart the server because the config has changed

**Comment by rosso-ptg** [comment]
The issue was that we were forwarding a 'clean' flag as buildOpts to the BuildServer. The BuildServer would compare the buildOpts with the ones used in the last build and restart if it detected any changes. This would be the case for the call off `node make` above, since the previous call included the 'clean' buildOpt.

Since the 'clean' flag is actually not needed as a buildOpt anymore (it is not evaluated in Builder.js), this has been resolved by removing the 'clean' flag from the buildOpts.
