### ISSUE TITLE
window title gets lost

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3959]
The client doesn't set the document title correctly, which leads to problems down the line like this:

* Start the app and have at least one window open
* Click on the desktop tray
* See something along the lines of this:
![Screenshot from 2022-03-11 08-53-17](https://user-images.githubusercontent.com/22109738/157825527-5728fe52-0b4f-4625-aac6-a9f7a384ee57.png)

(note: that text _is_ the menu, it's not part of the text editor in the background, I just needed a white background for visibility)

tutanota v3.93.5
tutanota v3.93.6

**Comment by ganthern** [comment]
Same here on arch with `gnome-shell 1:41.4-1`. It fixes itself after login and the menu uses the logged in mail address as a label, so it's not too bad if you auto-login.

**Comment by ganthern** [comment]
The menu should display the result of `BrowserWindow.getTitle`, which is ` document.title` of the `WebContents`.
Apparently it displays `window.location.search `instead.

* The index-desktop.html packed in 3.93.5 and 3.93.6 contains the expected `<title>` tag
* there is a short flash where a new window has the correct title before the menu breaks

**Comment by ganthern** [comment]
turns out this is a web app problem that first occured in 350d5225336381302852b1c6c155484d931f012f

after this line, the window title is messed up
https://github.com/tutao/tutanota/blob/350d5225336381302852b1c6c155484d931f012f/src/app.ts#L349

i think it's because of this:
https://github.com/tutao/tutanota/blob/350d5225336381302852b1c6c155484d931f012f/libs/mithril.js#L1208

**Comment by ganthern** [comment]
it was fixed in 4889fc8b3684b9d2a3ba897b90450b5ede483ad3
