### ISSUE TITLE
Offline Error in MailEditor is handled inconsistent with other offline errors

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#4024]
Should show a snack bar instead of a blocking dialog

**Comment by johnbotris** [comment]
# Testing
Do the following when you have no connection:
* When saving a draft from the mail editor (Ctrl+S), a snackbar is shown instead of a blocking dialog
* When sending a mail from the mail editor, a snackbar is shown instead of a blocking dialog
* when minimizing the mail editor, no snackbar is shown, but the error is mentioned on the minimized editor

Regression test a bit:
* When other errors occur on save, the error will be shown either as a dialog or as an unhandled exception
* When other errors occur on minimize, the error will be shown either as a dialog or as an unhandled exception
* When other errors occur on send, the error will be shown either as a dialog or as an unhandled exception (e.g. non-existent tutanota addresses)
