### ISSUE TITLE
[android] The notification icon stating "Tutanota is using battery"

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#439]
Uninstalled because of a one major issue. The notification icon stating "Tutanota is using battery". No matter what settings I chose, in and/or out of the app, it was still up there.
Solution?

Running on Moto G6 Play - Android 8.0.

**Comment by charlag** [comment]
"""
This behavior is now documented: https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_MIN

    Min notification importance: only shows in the shade, below the fold. This should not be used with Service.startForeground since a foreground service is supposed to be something the user cares about so it does not make semantic sense to mark its notification as minimum importance. If you do this as of Android version O, the system will show a higher-priority notification about your app running in the background.

And also here: https://material.io/guidelines/patterns/notifications.html#notifications-settings

    In Android O, a channel’s default importance level for foreground service notifications must be at least IMPORTANCE_LOW so that it shows an icon in the status bar.

    Channels using the less-prominent IMPORTANCE_MIN level will trigger an extra notification from Android at IMPORTANCE_LOW, stating that the app is using battery.

Sidenote: This is a real pain for us, since prior to O we used to dynamically switch between PRIORITY_DEFAULT and PRIORITY_MIN when our foreground notification had no interesting information to present. With channels we can't change the IMPORTANCE dynamically anymore, and had to remove that feature.
"""

https://stackoverflow.com/questions/45485460/is-it-possible-to-put-a-foreground-service-notification-in-a-notification-channe

I'm not sure what to do about this. At least we can avoid setting `PRIORITY_MIN` on >= O because it will be ignored anyway. Users can adjust its importance on O easily but I don't feel quite confident asking people to do this. At least we shouldn't get this "Tutanota is using battery" notification anymore.

**Comment by charlag** [comment]
I've made couple of experiments and it seems like no matter what importance notification channel has, it is we receive annoying "app is using battery" notification.
People experience it too
https://stackoverflow.com/questions/46335274/android-oreo-persistent-notification-app-is-running-in-the-background#comment87098702_46341735

**Comment by charlag** [comment]
Okay, if I uninstall the production app (which causes this notification too) then debug version of the app doesn't cause "app is using battery" notification to appear if `IMPORTANCE_LOW` is set. It is probably some bug in the system which should not affect production.
