### ISSUE TITLE
Change attachment layout in mail viewer

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4411]
**Ui proposals**
This approach might be a little bit more consistent in user navigation but we need to play around with really wide screens. It also does not use the bubbles anymore as we have the buttons available already.

One attachment
![Image](https://user-images.githubusercontent.com/8296817/181753020-fd9f433b-1c2d-4b81-98f6-48224e7c0d46.png)

Multiple attachments - collapsed
![Image](https://user-images.githubusercontent.com/8296817/181753021-963d19d8-1ca1-421a-af5e-f716b64accf0.png)

Multiple attachments - expanded
![Image](https://user-images.githubusercontent.com/8296817/181753022-05016168-107e-414e-a6bc-8b0da120ab52.png)

**Comment by paw-hub** [comment]
So I went and implemented a quick working demo on top of Tutanota's current UI, and here is what it looks like on a widescreen display.

In normal usage, the window will look like this:
![image](https://user-images.githubusercontent.com/104824185/182788894-edc940dd-a9a5-451f-bade-07ddefb06086.png)

When stretched, the window will look like this:
![image](https://user-images.githubusercontent.com/104824185/182788983-ba00a29c-9ce2-4f8e-824e-24e3ee83b13b.png)

And if we made just the attachments handle widescreen displays, it looks like this:
![image](https://user-images.githubusercontent.com/104824185/182789095-54ea5e23-20fd-4848-8432-e428d5369f66.png)

It seems if you set a maximum width on just the list, it will not be aligned with the rest of the mail. You could have it left aligned and the right side won't be aligned. And you could have it right aligned, but the left side won't be aligned. Center alignment gives a more neutral appearance, but it doesn't go with the rest of the mail, either.

After a short discussion with a couple people, we think it would probably be even better if widescreen support was a considered for the entire mail viewer's UI rather than just attachments, as that would allow the attachments to look more in place with the rest of the viewer, too.

**Comment by paw-hub** [comment]
So we have a branch [new-attachments-view-4411](https://github.com/tutao/tutanota/compare/new-attachments-view-4411)

The proposed list method is really nice, but we couldn't come up with a way to make it work at both lower and higher resolutions. I noted what the issues were at higher resolutions in my previous commit, but lower resolutions resulted in some more annoying issues, too, since we need room for both the attachment and the download button (and possibly an Open button).

As a list:
![image](https://user-images.githubusercontent.com/104824185/183431965-ea19c7ea-7b8c-4ffd-8f14-f72b70dd0105.png)

To make matters worse, some clients have some of these buttons disabled such as the web client having no Open button:
![image](https://user-images.githubusercontent.com/104824185/183432639-6eb3f2ec-578c-457c-90aa-30dfd10bc31b.png)

We decided for now to stick to the old styling and just fix the problem with the buttons being in a weird location in between attachments.

![image](https://user-images.githubusercontent.com/104824185/183430766-6c844e59-029b-4c0c-ba40-593885bd2dca.png)

![image](https://user-images.githubusercontent.com/104824185/183431008-98bac454-0b9e-4eba-b13e-2afe16cb8779.png)

![image](https://user-images.githubusercontent.com/104824185/183431199-d3ad6f64-49c2-4151-8f4f-0a18ae900bea.png)

**Comment by charlag** [comment]
Design work was done in #4290
