### ISSUE TITLE
search stops working after clicking a result and using system back button

### ISSUE THREAD

**Issue by alexbeattie42** [tutao/tutanota#4621]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When using the search functionality, it is not possible to search for something else after the first search is made. Regardless of if there are results for that search term, the search results are blank. 

**To Reproduce**
1. Open the mobile app
2. Click the search button
3. Type a search term for which you know emails will match the search
4. Click on one of the emails
5. Navigate back from the email (back swipe or press). You will now be at the home screen
6. Return to the search tab
7. Attempt to search for any term

**Expected behavior**
It should be possible to search again after making an initial search. 
The search results from the initial search should also be saved/cached.
In the navigation flow, back should take me back to the search page, not the home page. 

**Smartphone (please complete the following information):**
 - Device: pixel 3
 - OS: Graphene OS (Android 12)
 - Version: Tutanota v3.98.24

**Additional context**
You can reset the search by killing and rebooting the app.

**Comment by charlag** [comment]
Hi
It took me some attempts but I've managed to reproduce the issue. It is important to use system back key and not in-app one.

**Comment by nokhub** [comment]
Tests only need to be performed on Android, because the system back button is available only there.

## Test Notes

* [ ] search for an email and select it
* [ ] in-app back button leads back to the searched emails
* [ ] system back button shows the same behavior
* [ ] select a searched email again
* [ ] search works after using the in-app back button
* [ ] search works after using the system back button
* [ ] while in the search overview, the system back button leads to the inbox
* [ ] on tablet (multi-column layout), clicking the system back button in the search view leads to the inbox, even if an email is selected

## Regressions

* [ ] system back button for modals still works
* [ ] system back button closes opened sidebar in MailView
* [ ] system back button closes opened sidebar in SearchView
* [ ] system back button closes opened sidebar in ContactView
* [ ] system back button closes opened sidebar in CalendarView
* [ ] system back button leads from the opened contact to the contacts overview
