### ISSUE TITLE
Slow Login on Native Platforms

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4723]
Login takes 30s or more. Users seem to have a big search index (at least a few years). Might be related to search index or offline cache (more likely as it started to happen with offline only).

v3.102.3, v3.103.3

**Comment by jomapp** [comment]
### Reason
After some investigation we found out that the slow login on Android is caused by the following **two steps** during login:

1. Clear out unneeded data from the offline database ( i.e. trash and spam lists, data older than `timeRangeDays`)
2. SQL call `VACUUM`, which _clears_ and _defragments_ the database

### Possible solution
As discussed with @charlag we propose the following solution to solve the problem:

1. Move call to _clear out unneeded data_  to be executed after login and after successful synchronization.
2. Switch to [incremental vacuum ](https://www.sqlite.org/pragma.html#pragma_incremental_vacuum) and run SQL `VACUUM` query in `onStop` (when the user / system closes the app)

**Comment by yakMM** [comment]
Thank you for this, it's so much better now <3
