### ISSUE TITLE
Android themed icon

### ISSUE THREAD

**Issue by Lawatini** [tutao/tutanota#4735]
The colors of the Tutanota Android app icon seem to be reversed, the background should be dark and the middle of the icon colored.

![signal-2022-11-12-214458](https://user-images.githubusercontent.com/75477785/201493902-e18d2889-c53a-4bb7-abed-d134755e8d78.png)

**Comment by ganthern** [comment]
Usually, the path on the icon is the background color for us.

**Comment by Jegah** [comment]
Hi,
Could this be reconsidered?
Right now, the Tutanota icon is the only that looks likes it is inverted in both the light and dark mode of the system. That kind of defeats the purpose of having an adaptive icon that is suppose to fit the rest of the system.

![In dark mode](https://user-images.githubusercontent.com/105675997/230488891-765eba82-ba34-405d-a00b-821f24ee6522.png)
In dark mode

![In light mode](https://user-images.githubusercontent.com/105675997/230489032-be3f1cfe-7744-41e2-b658-3065a473eee4.png)
In light mode

Both icon icon should be swapped, so that it fits with the other icons.
