### ISSUE TITLE
Technical clarification for reschedule occurance of repeating event.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4872]
In order to start with #4860 we want to clarify some technical questions first.

* [x] Is the rescheduled event part of the repeating event or not?
* [x] How to support invitation for such an event?
* [x] How are rescheduled events supported by ical specification.
* [x] How do other providers handle the situation?
* [x] What about editing repeating rule for the rescheduled event?
    * [x] Do we display repeat rule when editing the rescheduled event?
    * [x] Do we allow changing it? Make research of how it is for other apps
* [x] How to model rescheduled occurrences? Propose a model definition
  * [x] How to map the rescheduled event to UID (important for incoming and outgoing invites).? 

**Timebox: 8h**

**Comment by nokhub** [comment]
### Is the rescheduled event part of the repeating event or not?

No, it is a separate VEVENT with the same UID and a RECURRENCE-ID and no RRULE.

### How to support invitation for such an event?
seems to be best to always send the parent event and all rescheduled instances when anything is updated or on initial invite. there's no indication on the original event that anything was rescheduled otherwise (this probably has implications for rendering/loading as well)

### How to map the rescheduled event to UID (important for incoming and outgoing invites).?
?

### How are rescheduled events supported by ical specification.
see below: add a VEVENT with the new start time/duration, give it the same UID, no RRULE and a RECURRENCE-ID

### How do other providers handle the situation?

 **Google Calendar rescheduling**
* default: a repeating event gets a UID and a RRULE. it only occurs once in exports
* with reschedule: each rescheduled instance gets the same UID as the parent event. It also gets a RECURRENCE-ID which is the start time of the original instance as dictated by the parent events repeat rule.
* the parent event and each rescheduled instance occurs in the export.
* repeat daily, move an instance to the day before,then change the rrule on that instance to every three days -> the rescheduled instance we just edited gets deleted because the original occurrence is not part of the RRule anymore

**Comment by bedhub** [comment]
* What about editing repeating rule for the rescheduled event?
* Do we display repeat rule when editing the rescheduled event?
*  Do we allow changing it?
    → We need more research on this

**Comment by wrdhub** [comment]
### What about editing repeating rule for the rescheduled event?  Do we display repeat rule when editing the rescheduled event?

Others show only info for the current event being looked at. One has a "view series" option where you can then edit the series, and will ask when you first select edit on the event if you want to edit that event, all, or future. Another does not have such a "series" view and will ask if you want to edit only the current event or the whole series on save.

Currently, when we select an event that is in a recurrence, it will display the date of the first event in the series. A proposed solution would be to display only the selected event (rescheduled or not), and then include "This event is part of a series" with the option to Edit all Recurrences or "Edit this and future Recurrences" both would then allow for the editing of the recurrence info. 

### Do we allow changing it? Make research of how it is for other apps

Others allow this. I would say yes.

### How are rescheduled events supported by ical specification.
This may provide some insight? https://icalendar.org/iCalendar-RFC-5545/3-8-4-4-recurrence-id.html It mentions: "the calendar application could simply truncate the unbounded recurring calendar component (i.e., with the "COUNT" or "UNTIL" rule parts), and create two new unbounded recurring calendar components for the future instances." In the case of changing the repeat rule for future events, this may be the solution.

**Comment by charlag** [comment]
# How do we make rescheduled events work with UID

## Usages

Currently, we only need UIDs to deal with calendar invites. We look up database events by UID.

We might also use UID later to link together original and rescheduled occurrences.


## Options

1. Change `CalendarEventUidIndex` to point to multiple `CalendarEvent`s. We need to take care of old clients
overwriting it with a single value. This way we can look up all the rescheduled occurrences by UID.
2. Invent some hack with UID so that we still have single `CalendarEventUidIndex` per event still. e.g. we can
append `--tutanota-rescheduled-uid-${eventId}` to the rescheduled occurrences. This way we don't need to change
the model but we need to make sure to strip away before doing lookup. This way we can still look up other occurrences
by UID.
3. ???

## Notes
No matter which option we will pick we need to make sure to include enough information in invites to reproduce
the same event sequence on the receiver's side. If we invite others to all the occurrences (this is not decided?)
then we need to make sure to send all of them. This is again something to think of regarding old clients: old
client might send an invitation incorrectly or can process is incorrectly.

**Comment by ganthern** [comment]
The somewhat open questions I can see now are the following:
* put rescheduled events into short or long events -> they never actually repeat, so I would say handle them like non-repeating events
* how to make the reference from main event to rescheduled recurrences -> we should not start putting information into Ids that then needs to be parsed out, there's a world of pain there. updating the index to handle lists of event ids seems reasonable.
* old client modifying the CalendarEventUidIndex -> the server should be able to translate a single event Id to an array with one element?
* old client sending invites for an event with rescheduled recurrences -> currently, it'll always just send the original event without any trace of the reschedulings, which are invisible to the inviter anyway. receiving them is fine for other old clients and new clients because they will still add exactly what the inviter saw to their calendar.
* old client receiving an invite from the new client -> there's probably going to be multiple events in the invite, main event and rescheduled events. old clients only retrieve the first event from an ical file in a mail, but can handle files with multiple events. there's potential for unintentional data loss here.

**Comment by charlag** [comment]
So my fear with separate entities for rescheduled occurrences was that they must always be in scope when we calculate occurrences. Meaning that if rescheduled events repeat (I am not sure why you say they can't? What about splitting the event, does it get its own UID?), if they repeat, then we will load them anyway and if they do not then we will load them as soon as we would need to display them.

We just need to adjust the algorithm which places events on days to check for other events with the same UID on that day and pick the appropriate one.

I am completely at loss about alarms though.
