### ISSUE TITLE
[Need explanation] F-Droid mentions non Free network service

### ISSUE THREAD

**Issue by prog-amateur** [tutao/tutanota#520]
Hello, I am happy to see Tutanota on F-Droid. 
However, on the description, it is mentioned that the app promotes non-Free network services. 

Please, could you clarify what does it mean ? I through that Tutanota was entirely open-source, is it really the case ? 

Thank you very much for your feedback.

**Comment by charlag** [comment]
Please don't ask general questions on GitHub.
Tutanota client is entirely open source but server side is not published. There are multiple reasons for the but one of the biggest ones is that we don't have enough resources to support server as an open-source project now. That's why F-Droid added this badge. You can check the discussion here:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3468
Hope it answers your question. Please, use support email in the future.

**Comment by X-Ryl669** [comment]
Is there a documentation of the protocol used (at least) so it would allow a free-server implementation ?
