### ISSUE TITLE
Indication for previous conversation entries

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5252]
## User story
As a user, i want to see that there is more content above my selected mail in the conversation view so I don't have to look for previous conversation entries in the list because i forgot I can just scroll up.

## AC
* The ending of previous mail is visible above the selected email by default.
* If there is no previous email the mail shows up at the top
* the location of the action buttons does not change when scrolling through conversations with and without previous mail with the up/down keys

## Tasks
* [ ] adjust the scrolling algorithm to give enough space above the focused/active mail to show the bottom of the previous mails card and make sure that this is always possible and applied (even if there is no previous card)

**Comment by wrdhub** [comment]
So the solution I came up with looks like this:


![Image](https://user-images.githubusercontent.com/119855382/226297834-6fc004c1-c22f-4b0c-91e0-63190a16d0af.png)

Which is fine, but there is an edge case when displaying the first email after a subject change:


![Image](https://user-images.githubusercontent.com/119855382/226298016-f2b7e46b-6f81-45cc-94a0-7d27f5fcaf93.png)

It won't pick up on the new subject. Extending the detection range runs into issues with displaying a long subject:

![Image](https://user-images.githubusercontent.com/119855382/226298155-f28bad68-2214-477b-9a1d-0ddb22f076a8.png)

And other solutions (like not displaying the floating subject in that case) run into issues of their own (because of how frames are rendered). We want to move away from the current design anyway, and to a toolbar. This is getting shelved until we decide what to do next.

**Comment by wrdhub** [comment]
This should be covered by the new toolbar UI, waiting for feedback.
