### ISSUE TITLE
Improve custom spam rules

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#547]
Ideas how to improve custom spam filter
* rules for to, cc, bcc recipients
* when setting up a rule for a domain the rule should also match subdomains.
* allow TLD

* Spam dialog for emails/domains could be defaulted to No Spam when launched from the spam folder and "Always spam" when launched from the Inbox. Add option to edit existing entry

* Allow filter by subject (only for unencrypted email)

**Comment by bedhub** [comment]
User have also requested to disable spam filter completly. Maybe we can allow a wildcard operator like * which can cover both case "whitelist all" or "blacklist all".

**Comment by mebarc** [comment]
Further requests were about possibilities to merge several rules, e.g. by allowing operators like "AND", "OR".

**Comment by armhub** [comment]
When moving an email out of the spam folder we could offer to add a whitelisting spam rule for the sender. We could do this with a notification instead of a dialog.

**Comment by mtrovo** [comment]
It would be nice to have a whitelist, somehow I'm receiving some newsletters and my bank emails on the spam folder and as today there's no way to mark them as not spam. For me the workaround is to check the spam folder for new emails as any other folder.

**Comment by charlag** [comment]
There's a "no spam" rule in the global settigs->spam rules

**Comment by jeythekey** [comment]
Adding to armhub's suggestion, it would be nice to have a "no-spam" button at the head of a spam mail. Such a button would be expected for a mail classified as spam and this button would then also be expected to trigger the no-spam-rule action.
Furthermore, for mailing lists, if possible, I think it would make sense to add the technical sender instead of the from-field.
And for bulk-actions (selecting several mails and dropping to inbox) the no-spam-rule action should also be triggered. (By the way, to have a context menu entry for this case "no spam" or "move to inbox (and add white-rule)" would be nice.)

**Comment by renatolond** [comment]
What I miss the most is a blocklist of to/cc/bcc. I have some catch-all domains set up and I would like to be able to say that emails to `spammy@domain.com` should be rejected.

**Comment by huzzam** [comment]
Honestly, there needs to be heuristic filtering of incoming email content to determine spam status. Blocklists are not very effective, as sender addresses are easily spoofed.

**Comment by l0f4r0** [comment]
I would suggest one more thing: priorize folder rules over spam rules so spam rules only apply for the remaining emails still in inbox folder (like the feature in Thunderbird).

**Comment by charlag** [comment]
@l0f4r0 it's not possible: inbox rules are executed on the client and spam rules are on the server

**Comment by bedhub** [comment]
- blacklisting single email address fails if whitelisting TLD / *
- whitelisting single email address fails if blacklisting TLD/ *

**Comment by bedhub** [comment]
fixed on server
