### ISSUE TITLE
Add ability to minimize draft dialog

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#587]
# Test notes

Test on all of: 

**three column layout (desktop)**

- [x] Minimze editor -> check that draft is saved
- [x] Minimize -> reopen -> send : check that draft is sent.
- [x] Minimze editor -> Continue editing in draft folder : Minimized editor opens
- [x] Minimize editor -> open new draft and minimize it too: New editor is minimized, with count "2"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> close minimized "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> go to Drafts and delete "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft -> delete it while it is saving: it is deleted from Drafts after a while
- [x] Minimize draft while offline: minimized editor says draft was not saved
- [ ] Minimize draft while offline -> open minimized draft: all content is still available
- [x] Check that layers in the application are handled correctly. Minimized editors should be behind the modal dialogs (e.g. progress dialog/ mail editor)

**two column layout (tablet)**

- [x] Minimze editor -> check that draft is saved
- [x] Minimize -> reopen -> send : check that draft is sent.
- [x] Minimze editor -> Continue editing in draft folder : Minimized editor opens
- [x] Minimize editor -> open new draft and minimize it too: New editor is minimized, with count "2"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> close minimized "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> go to Drafts and delete "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft -> delete it while it is saving: it is deleted from Drafts after a while
- [x] Minimize draft while offline: minimized editor says draft was not saved
- [ ] Minimize draft while offline -> open minimized draft: all content is still available
- [x] Check that layers in the application are handled correctly. Minimized editors should be behind the modal dialogs (e.g. progress dialog/ mail editor)

**single column layout (mobile)**

- [x] Minimze editor -> check that draft is saved
- [x] Minimize -> reopen -> send : check that draft is sent.
- [x] Minimze editor -> Continue editing in draft folder : Minimized editor opens
- [x] Minimize editor -> open new draft and minimize it too: New editor is minimized, with count "2"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> close minimized "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft "Foo" -> minimize draft "Bar" -> go to Drafts and delete "Foo": "Bar" is minimized, with count "1"
- [x] Minimize draft -> delete it while it is saving: it is deleted from Drafts after a while
- [x] Minimize draft while offline: minimized editor says draft was not saved
- [x] Minimize draft while offline -> open minimized draft: all content is still available
- [ ] Check that layers in the application are handled correctly. Minimized editors should be behind the modal dialogs (e.g. progress dialog/ mail editor)
- [x] When in single column layout editors should be and behind folder (foreground) column

**Comment by armhub** [comment]
We could minimize it into the "new mail" button and make it look different in this case.

**Comment by v011** [comment]
Hello. Another suggestion would be to add an arrow (downwardly directed) next to the "new mail" button and transform the action of this button to show a dropdown which could add the ability to edit several drafts. For information, some e-mail providers already propose similar feature.

The "new mail dropdown" button could show something like that just below.

```
+------------------------+
| New mail               |
+------------------------+
| Re: Invoice            |
+------------------------+
| Fwd: Discussion on ... |
+------------------------+
```

You could limit the number of minimized drafts (e.g. to 5).

**Comment by armhub** [comment]
Here is the use case I think of: You are writing an email and just quickly want to have a look at some other email and then immediately continue writing your email.
Currently you have to do 5 clicks for switching back and forth: click close, click save draft, (check another email), click on drafts folder, click on draft, click on edit draft.

One solution would be that we add another item "Minimize" in the close button of the email. When you click it your draft is minimized which means it is kept in the background and the "New mail" button is changed to "Continue draft" or similar. When you click it your draft is opened again for editing. For this use case saving the minimized draft or having multiple minimized drafts or writing another email in parallel to the minimized draft would not be necessary as you anyway want to immediately get back to you draft. You would have 3 clicks instead of 5 currently but with keyboard shortcuts for minimizing and continuing it would even be just two key presses.

**Comment by v011** [comment]
Yes, I think it would be a good first implementation for minimized drafts. Decreasing the number of clicks et adding the ability to minimize with a keyboard shortcut will improve the ergonomics of the app. Restoring the minimized draft could be done with the same shortcut as for a new mail ("N").

**Comment by Aninstance** [comment]
Entirely agree. I've been a premium subscriber for a good few years now and have enjoyed using the service as its evolved. Kudos to the dev team, great work & much appreciated. The one issue that I'm constantly bumping up against is being unable to view other email whilst in 'composition mode'. I often need to flit back and forth to get info from previous emails, or to quickly check new email as it arrives whilst I'm in the middle of writing a new one.

Ideally, the composition modal would have a 'minimise' button, that instantly backgrounds it, perhaps to a floating widget of some kind. That would be a very significant UX improvement (for me, at least) and I'd guess relatively straight forward to implement.

**Comment by vitoreiji** [comment]
@bedhub and I looked at this and we are concerned that some actions may result in creating too many (possibly abandoned) drafts:

1. New > Minimize > Open > Close: Empty draft is saved without asking
2. New > Minimize > Open > Change > Close > Discard changes: Empty draft is saved
3. New > Change > Minimize > Open > Close: Minimized version is saved without asking
4. New > Change > Minimize > Open > Change > Close > Discard changes: Minimized version is saved
5. New > Minimize > Close: Empty draft is saved without asking

We could improve on this (for 1 -4) by adding a "Delete draft" action to the close menu and showing the menu also if closing an existing draft.

For 5, we could remove the "X" button from the minimized editor so the user would use the normal "Close" menu.

**Comment by bedhub** [comment]
Right now the "Minimized" action is an additional button in the header bar which is not great because It might not fit to have two buttons on either the left or right side. We tried that multiple time but we decided always against it when using button type "secondary" or "primary". To add multiple buttons we need to switch to icon style buttons and also get rid of the title inside the header like we did with calendar event preview component or template popup.

**Comment by bedhub** [comment]
**Idea 2: Always minimize before closing**
The idea is that when closing the editor we always show the minimized state and from there it is possible to delete/close/edit the draft. 

Delete: Remove minimize editor and moves the draft to trash,
Close: Remove minimize editor and keeps draft 
Edit: Removes minimizes editor and opens edit draft dialog.


![always-minimize-action-desktop](https://user-images.githubusercontent.com/8296817/122876461-d4b08e00-d335-11eb-9344-a5e1766e3a73.png)

![always-minimize-minimzed-state-desktop](https://user-images.githubusercontent.com/8296817/122876433-cebaad00-d335-11eb-962f-b46f1e908f72.png)

![always-minimize-mobile](https://user-images.githubusercontent.com/8296817/122876413-c7939f00-d335-11eb-8b02-d26db987b286.png)

**Comment by armhub** [comment]
The "Save" option is not explicitly visible any more in idea 2, so users may wonder how to save the draft.

**Comment by v011** [comment]
Maybe we should just rename "Close" to "Save".

**Comment by bedhub** [comment]
After a discussion with the team today we had the idea to add a small state message to the minimized state saying "Draft saved" or even a switch from "Saving" to "Draft saved" as we anyway save the draft automatically when minimizing. 

We will try to make the minimized editor smaller by using icon only "ActionLarge" buttons like in the calendar event preview.
![calendar-preview-icon-only](https://user-images.githubusercontent.com/8296817/122899589-3bd93d00-d34c-11eb-8d43-6ddcbb67ad23.png)

We prefer the second approach to go always through the minimized state. The advantage is that such a floating/overlaying element can exist across multiple views and the user is always able to continue writing the email. That option is not available if we would add the "continue/edit" button next to the "New email" button.

As we are always saving drafts now (even empty ones) we said that a "delete" action is useful in case the user decides to not write that email at all.

We think that the most common use case is the one that @armhub described (writing one email -> look something up -> continue writing -> send ) and having multiple of them is rather an edge case. We still have to handle that case as it is always to open/minimize a new mail editor but we should not concentrate on making multiple minimized mails accessible for the user. One solution could be that they are all stacked on top of each other, another one would be to just replace the minimized editor content.

**Comment by charlag** [comment]
@bedhub I want to just point out that I meant not "replace mail content" but "replace which draft we are displaying in the bottom"

**Comment by bedhub** [comment]
This is how it looks like now with icon only minimized editor
![minimized-editor-icons-only](https://user-images.githubusercontent.com/8296817/123056749-7fdd4800-d407-11eb-89d4-eb9f4a6ab7a0.png)

**Comment by vitoreiji** [comment]
## Update on Idea 2

Minimized editors now have a counter to show how many are in the stack.

![image](https://user-images.githubusercontent.com/197261/123291050-0d0cc380-d512-11eb-997d-0a862d2c1d17.png)

Previously this counter was attached to the New Mail button on mobile view, but we removed that, as well as the drop down menu from the New Mail button, and instead the we show the overlay on mobile as well. We also no longer make it full width, so it is easy to tap the mail that is currently under the overlay (useful for the last on the list). On single column layout, the edit button is not shown, but you can always edit by clicking anywhere on the overlay (other than Close, Delete and the counter)

![image](https://user-images.githubusercontent.com/197261/123291807-bfdd2180-d512-11eb-9e72-81bcd4a0a244.png)

There is always space at the end of the mail body, so the overlay does not hide any content, you can just scroll

![image](https://user-images.githubusercontent.com/197261/123292262-2bbf8a00-d513-11eb-96e6-2f1fffcb46bb.png)

The button is called "Close" again, instead of "Minimize". This always saves the draft and creates a minimized editor.

![image](https://user-images.githubusercontent.com/197261/123292632-8658e600-d513-11eb-9113-4705a738f1e7.png)

**Comment by vitoreiji** [comment]
Test notes

- [ ] Minimze editor -> check that draft is saved
- [ ] Minimize -> reopen -> send : check that draft is sent.
- [ ] Minimze editor -> Continue editing in draft folder : Minimized editor opens
- [ ] Minimize editor -> open new draft and minimize it too: New editor is minimized, with count "2"
- [ ] Minimize editor -> open new draft and minimize it too -> close minimized editor: Original editor is minimized, with count "1"

**Comment by charlag** [comment]
In 2 column layout (also on desktop) dialogs are behind the drawer layer.
It might be okay but we need to close the drawer then I think.

![DB103651-E66A-4613-BCF8-625ED1D84E33](https://user-images.githubusercontent.com/3099142/124242271-dab82300-db1c-11eb-9cb4-208fada0d3dd.png)

**Comment by charlag** [comment]
If you are offline, add inline image, minimize and reopen inline image won't be shown

**Comment by charlag** [comment]
> If you are offline, add inline image, minimize and reopen inline image won't be shown

and online too actually
