### ISSUE TITLE
empty lines are duplicated when copied from composer

### ISSUE THREAD

**Issue by terminal-root** [tutao/tutanota#5912]
**Bug in web app and desktop app**

empty lines are duplicated when copied from composer

**To Reproduce**
1. begin composing a new message or editing any other HTML (event description, notification email, out of office notification)
2. type a message containing empty lines.

![image](https://github.com/tutao/tutanota/assets/24536673/d44c37d1-1051-475a-b634-d01ce8cd3fb5)

3. copy the message to a text editor

**Actual Behavior**
The empty lines in the message are duplicated.

![image](https://github.com/tutao/tutanota/assets/24536673/bb3fbd16-5791-4622-a292-4484d21d8d0e)

**Expected behavior**
The copied message is identical to the original.

![image](https://github.com/tutao/tutanota/assets/24536673/16ade092-cc69-4850-828e-69a24a4e021c)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37 (Xfce) x86_64
 - Browser: Mullvad Browser
 - Version: 12.5.4
 
**Additional context**
- Tutanota Desktop Version: v3.118.8

- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

### Test Notes 
* test this in firefox, chrome, safari, desktop, both mobile platforms
* also try selection only parts of the editor contents before copying/pasting
* [ ] the bug does not reproduce anymore
* [ ] all the formatting functions in the rich text editor still work
* [ ] inline images are still attached correctly
* [ ] numbered and unnumbered lists are still created after typing `1. ` or `* ` at the start of a line
* [ ] copying and pasting HTML from/to the editor works as expected

**Comment by ganthern** [comment]
Confirmed with firefox on ubuntu. This is a huge problem for all the whitespace programmers that use tutanota as a version control system.

Jokes aside, thank you for the report @terminal-root!

**Comment by ganthern** [comment]
Analyzed a bit more:
* works: Safari -> Text Editor on MacOS
* works: Firefox -> LibreOffice on Windows
* does not work: Firefox -> Notepad on Windows
* does not work: Firefox -> gedit on ubuntu
* does not work: Chromium -> gedit on ubuntu

Squire puts one `text/plain` string into the clipboard data that contains the duplicated newlines and one `text/html` string that does not. We can override the `text/plain` one with the result of `squire.getSelectedText()` in the copy event handler of the dom element and fix this bug, because the result of that call does not contain the duplicated newlines for some reason. the `text/html` remains unchanged and is also what's used when copying/pasting stuff around in the editor itself.

Note: Another problem that presents itself currently is that we can't copy inline images and paste them back anywhere, which is possible in the squire demo (because we replace inline images).

**Comment by rezbyte** [comment]
Tested this across firefox (on Ubuntu), chrome, desktop, both mobile platforms. @charlag tested this on safari.
Uncovered the following bugs while testing: #6091, #6096, #6097, #6098.
