### ISSUE TITLE
Email folder name popup does not fit on screen

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6162]
## Issue
When looking at at email, if you hover over the folder icon by the time it will show the name of the folder that the email is in. If the folder name is long enough, it can overflow and the name can be hidden.

![Screenshot from 2023-11-15 11-07-02](https://github.com/tutao/tutanota/assets/119855382/ae66c0c1-236c-4e90-a107-0b6a58d46b5e)

The popup should be moved over enough that the full name is visible. I have only seen this in desktop, but mobile apps should be checked too. 

## Notes
I think the issue is similar to the previously fixed file attachment popup issue (#5919), so the solution may be similar.

## Test Notes
- [ ] The far left of the icon tooltip is at the bottom left of the icon if it would overflow and is fully visible
- [ ] The far left of the icon tooltip is at the perfect bottom of the icon if it wouldn't overflow and is fully visible

**Comment by ganthern** [comment]
can confirm that this happens:
* open a mail and show the tooltip:  everything's fine
* change the name of the folder to something shorter or longer: the tooltips left edge is still aligned where the longer one would have been
  * therefore, it's either too far left or cut off at the right

since this is fixed by just switching to the next mail or folder, I would not hold up the release for this.

**Comment by charlag** [comment]
It was on Linux and I didn't change any folder names but I also think it's minor

**Comment by rezbyte** [comment]
> It was on Linux and I didn't change any folder names but I also think it's minor

How were you setting the folder names? By editing with the dev tools or creating a new folder with the name?

**Comment by rezbyte** [comment]
I see. In that case, this is something worth looking into.
