### ISSUE TITLE
Basic encrypted calendar

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#628]

**Comment by x80486** [comment]
Yeah...we need that also!

**Comment by thenaturalist** [comment]
The lack of any valid calendar functionality unfortunately is a total show stopper for me. 

Absolutely love Tutanota and how you have solved encryption, but not being able to interact reasonably with any calendar invites or add an account via IMAP so that invites would be shown there basically kills Tutanota for me.

**Comment by snaggen** [comment]
I would love to see some cooperation with https://www.etesync.com/ for contacts/calendar/tasks integration.

**Comment by TheGoldmasterCorporation** [comment]
what about sync with nextcloud?

**Comment by janpetras** [comment]
Even if a calendar is implemented, if there is no contacts feature as well which integrates seamlessly with the calendar and the email too - then said calendar is useless. I'm currently using fruux.com in an effort to stay away from Google - it has Calendar, Tasks and Contacts - similar to the Google suite. I'm paying for it, but I'd happily move over to Tutanota so that I have email integration with everything as well.

**Comment by jalanningjr** [comment]
Is there a timeline as to when we might see Tutanota release an encrypted calendar?

**Comment by jalanningjr** [comment]
Is there a timeline as to when we might see Tutanota release an encrypted calendar?

**Comment by gio-cefalu** [comment]
Is there any update on the calendar?  This is absolutely the single most important new feature for me at the moment.  I have been waiting since I saw this as an item under review in early 2015: https://tutanota.uservoice.com/forums/237921-general/suggestions/6986446-an-encrypted-calendar?page=1&per_page=20

We're now almost halfway through 2019, which is 4.5 years after it was first under review, and it was "planned" for release repeatedly.  Folks like myself have been paying customers, often donating yearly on top of our subscription, and waiting patiently for quite a while.  Do we have a status update on the calendar?

**Comment by charlag** [comment]
Current status is "design and planning". We need to tick several minor tasks (and we will start working on it, at least that's the plan.
Thanks for your patience, we know you're waiting for it.

**Comment by janpetras** [comment]
> Is there any update on the calendar? This is absolutely the single most important new feature for me at the moment. I have been waiting since I saw this as an item under review in early 2015: https://tutanota.uservoice.com/forums/237921-general/suggestions/6986446-an-encrypted-calendar?page=1&per_page=20
> 
> We're now almost halfway through 2019, which is 4.5 years after it was first under review, and it was "planned" for release repeatedly. Folks like myself have been paying customers, often donating yearly on top of our subscription, and waiting patiently for quite a while. Do we have a status update on the calendar?

I agree. They haven't actually properly improved this in any way since launch. They just keep pushing updates with 'minor bug fixes' and 'performance improvements' but nobody notices any performance anything. It's still slow, it's still limited in functionality.

They launched the desktop client which nobody asked for and is basically just a website wrapper that a 5 year old can make in 20 minutes, and now some horsecrap 'secure way to contact website admins' which again, nobody asked for - but a calendar? something actually useful? heresy!

I advise you do what I did and take your toys over to proton or mailfence.

**Comment by mpfau** [comment]
This is not a discussion forum but our issue tracker. Please use our reddit forum if you want to discuss. Thanks!

**Comment by armhub** [comment]
The basic encrypted calendar (first release) will include the following features:

- One personal calendar per user
- Daily view
- Monthly view
- Upcoming events view
- Recurring events
- Notifications for events
- Event fields: title, description, location, duration/full-day/start time/end time

All other features will be included in later releases.

**Comment by Aneyrin** [comment]
> The basic encrypted calendar (first release) will include the following features:
> 
>     * One personal calendar per user
> 
>     * Daily view
> 
>     * Monthly view
> 
>     * Upcoming events view
> 
>     * Recurring events
> 
>     * Notifications for events
> 
>     * Event fields: title, description, location, duration/full-day/start time/end time
> 
> 
> All other features will be included in later releases.

Thank you for great news! Will it support caldav in this/next release?

**Comment by gio-cefalu** [comment]
Does that include the ability to send and receive calendar invites, at least to other Tutanota users?

**Comment by armhub** [comment]
We will probably not support caldav because the Tutanota calendar is end-to-end encrypted and caldav does not support this. Invites will be supported later.

**Comment by Aneyrin** [comment]
Is there any way to sync this calendar with iOS/Android?

**Comment by snaggen** [comment]
@armhub That is one more reason to build on etesync, they have both working android sync support and a CalDav proxy that will allow regular caldav applications to work. I don't understand the need to reinvent the wheel, especially if you have limited resources.

**Comment by mpfau** [comment]
@snaggen This feature request is not about integrating with a third party. It is about a calendar implementation as part of Tutanota. Please discuss your feature request on the reddit forum. Thanks!

**Comment by snaggen** [comment]
I know that, but since etesync is opensource there is no reason you cannot build your service on that as part of Tutanota. The upside would then be that you would be able to reuse other parts also, by modifying them to your needs, like the android sync and caldav proxy.

**Comment by BPA-vt** [comment]
any idea when the calendar will be implemented?

**Comment by charlag** [comment]
We are working on this actively. I would say in June but I don't want to give guarantees.

**Comment by BPA-vt** [comment]
Thanks for your response Ivan. Looking forward to using this feature. 

Cheers, 

Brian 
Brian P Allen 
PO Box 77 
South Pomfret, VT 05067 
802-457-3469 
Mobile 802-291-1036 

Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com



May 28, 2019, 2:29 AM by notifications@github.com:

**Comment by JimmyCushnie** [comment]
For people following this issue, they posted an early picture of the Calendar on twitter. https://twitter.com/TutanotaTeam/status/1135229989413171201
![image](https://user-images.githubusercontent.com/32693298/58766024-cbcea300-8547-11e9-8aa8-426af4eecfcd.png)

**Comment by BPA-vt** [comment]
Thanks for this update! 

B
Brian P Allen 
PO Box 77 
South Pomfret, VT 05067 
802-457-3469 
Mobile 802-291-1036 

Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com



Jun 2, 2019, 3:05 PM by notifications@github.com:

**Comment by gio-cefalu** [comment]
Any update on this? Will we be able to beta test this sometime soon?

Thanks.

**Comment by charlag** [comment]
We are done with pretty much everything, we've been working on encrypted alarms recently. We have to finish couple of smaller things and test it.

**Comment by gio-cefalu** [comment]
Awesome.  Thanks so much.  I can't wait!

**Comment by armhub** [comment]
- lines between days in the month view are sometimes not visible on Edge
- The red dot of the current time line in the day view is not centered on the vertical line
- Reminder 5 minutes "before"
- Event delete button on Edge has no margin to the bottom right

**Comment by gio-cefalu** [comment]
How do we see the calendar now?  I noticed this feature is closed on github, but I do not see the calendar available via browser or app, and I am on the Beta app for Android.

**Comment by armhub** [comment]
> How do we see the calendar now? I noticed this feature is closed on github, but I do not see the calendar available via browser or app, and I am on the Beta app for Android.

This issue is on milestone 3.55.0, so it will be release with Tutanota version 3.55.0, probably beginning of next week.
