### ISSUE TITLE
New contract amendment 4.8

### ISSUE THREAD

**Issue by prog-amateur** [tutao/tutanota#639]
Dear Tutao team, I have received the following email from your service : 

> "Hello,
> 
> we would like to inform you that for reasons of completeness we have added point 4.8 to our Terms & Conditions: "Tutao has the **right to show its customers security notices as well as information in regards to contracts** with the customers, to product updates, to Tutao GmbH, to other products and to products of partners. Partners are exclusively companies that can be recommended by Tutao GmbH because they advocate human rights, data protection or privacy." 

Please, could you clarify ? I am not sure it is RGPD compliant to give only generic words, which exact data do you share (what is "information"), and who are exactly your partners ? We know that Facebook and Google proclaim respect of privacy so it can be anything. For many companies it starts like that and then you never know which data is kept and for what/to whom it is shared (most of the time sold). 

Please, don't take it personal but I think to just send such email and wait for the 11/02 like many companies do is not the best option. 

Thank you for your understanding.

**Comment by mpfau** [comment]
Thanks for your question! 

We never share your data with other parties and section 4.8 is not about data sharing.

From time to time, you will receive information about companies or organizations that are our partners because they advocate human rights, data protection or privacy. And that is exactly what this amendment is about.
