### ISSUE TITLE
letters don't arrive

### ISSUE THREAD

**Issue by kargo123456** [tutao/tutanota#6435]
I write to addresses with the extension @mail.ru
And the answer began to come
Although there were no problems before, but in the last month it has constantly
 And the answer began to come

"This is the mail system at host w4.tutanota.de.
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.
For further assistance, please send mail to postmaster.
If you do so, please include this problem report. You can
delete your own text from the attached returned message.
The mail system
connect to mxs.mail.ru[**217.69.139.150]:25: Connection timed
out"

 [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by kargo123456** [comment]
please help
Thank you

**Comment by rezbyte** [comment]
Hi @kargo123456,
Sorry to hear you are having issues with sending emails to Russian addresses.

Unfortunately, Tuta Mail has been blocked in the Russian Federation since the 14th of February 2020. Because of this, you cannot send emails to addresses hosted in the Russian Federation including 'mail.ru'. [You can read more about it on our blog](https://tuta.com/blog/posts/tutanota-blocked-russia).
