### ISSUE TITLE
Old draft body not readable after updating it

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6516]
After saving an old draft (pre-blob) the body of the draft can not be displayed any more ("This element cannot be displayed correctly. If possible, please ask the sender to re-send this message.") When logging out and in again the body is correctly visible again.

We thought we had fixed this with https://github.com/tutao/tutanota/issues/6370 but the problem still exists.

When this problem occurs we can not resolve a session key of the MailDetailsDraft in CryptoFacade.resolveSessionKey(). The _ownerEncSessionKey is null. "details -> body -> compressedText" is set on the instance.

**Comment by Piscium** [comment]
Was bitten by this bug today. I had a draft with a good deal of text and now cannot access the draft. :(
First time this happened to me.
Is there any workaround?

**Comment by Piscium** [comment]
this happened on the fdroid app, v. 3.122.4

**Comment by charlag** [comment]
The issue won't occur on 218.240219.0 anymore

**Comment by Piscium** [comment]
> The issue won't occur on 218.240219.0 anymore

It happened with me on that version yesterday. You said it won't occur any more. Are you saying that some change was done on the server side since yesterday when I bumped into the issue to prevent it from occurring on that version?

**Comment by charlag** [comment]
@Piscium new client does not use outdated data format. I have notified responsible team that the issue still occurs.

**Comment by nadesco** [comment]
I also came across this `This element cannot be displayed correctly` bug. I've tried deleting the draft a number of times but have not been able to do so. If I highlight the message or check its box and then click the Trash icon nothing happens. The issue might be related to syncing because I think I originally deleted it on my Android device. It's only on the desktop client that the message lingers.
Tutanota v229.240514.1
Mac 14.5
