### ISSUE TITLE
some html emails cause rendering issues

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#6581]
We do not know much at this point, but the issue has been reported by multiple users.

Some HTML emails are not displayed in the mail viewer but are rendered correctly if exported or forwarded. 

When forwarding, these emails are rendered correctly in quoted text part of the email. 

## Test notes:
- [x] Pressing `i` on the keyboard while in the mail view opens the source code viewer
~Clicking on 'Show email source code' in the more buttons ('...') opens the source code viewer~
- [x] The source code viewer is scrollable if it's content will not fit on screen
- [x] The source code viewer's contents can be selected and copied

**Comment by charlag** [comment]
We want to add a shortcut to view email before HTML sanitizing, something like "view source"

**Comment by wrdhub** [comment]
This one probably shouldn't have been closed with that name (or the text changed to reflect that the goal was just to add a source viewer). Since senchden already opened a new issue (and I generally think new issues should be opened instead of reopening closed issues), I am going to close this one and continue with this issue under #6930
