### ISSUE TITLE
storage bug

### ISSUE THREAD

**Issue by kargo123456** [tutao/tutanota#6689]
I wrote more than once, but the support service ignores the message and only offers to switch to a paid tariff plan
I receive a message that my mailbox has reached its limit and some messages need to be deleted
I deleted a huge number of letters (about 300 megabytes), but the mailbox still does not clear and as a result I cannot use mail
![storage](https://github.com/tutao/tutanota/assets/157664719/31f18ba6-5e10-481b-ac69-4e1fadc136b1)
![Storage](https://github.com/tutao/tutanota/assets/157664719/9cc3ade6-0534-43a8-9ffc-6d41d8b1ef7c)

**Comment by kargo123456** [comment]
very slowly, but it seems the storage has started to clear

**Comment by rezbyte** [comment]
Hi @kargo123456 ,
I am sorry to hear you are still having issues with clearing up storage.

We are trying to attend to as many issues as possible however, we do not have the support staff to attend to all issues because we are a small company. This is why we only offer support to paid users at present. Please continue the discussion inside #6673.
