### ISSUE TITLE
Contacts management settings page shows wrong text 

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#6761]
Go to _contacts management_ settings page with selected app language English.

See the text as shown in the screenshot below.
![Screenshot_20240321-113739](https://github.com/tutao/tutanota/assets/17314077/f9b16cb6-64c2-4be2-8bdd-f29bf6828c7c)

Wrong: Text explains that two-way sync is **not** possible.

Should: Test explains that a two-sync works.

**Comment by MustachedMario** [comment]
Still not fixed on the latest iOS Verison, leads user in wrong "security", because this text says tuta contacts are "write protected", but since 2-way sync introduced, tuta contacts can be manipulated/killed from buggy tuta sync process (#6798, #6767) or by an app. Lost all comments on tuta contacts this way!

**Comment by wrdhub** [comment]
Updated in our translations.
