### ISSUE TITLE
Spike: Contact sync improvements

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6811]
### User story

After importing contacts from my device and enable contact synchronization i expect that there are no duplicate contact entries in my native address book.

### Notes:
We have some ideas to improve the situation 
* We could inform users that iCloud sync is on. Recommend to turn it off and link them to the iOS setting to have the best contact sync experience
* Doe not create contact copies but rather try to identify native contacts and add them to the group.

Related issue https://github.com/tutao/tutanota/issues/6773

### Spike

Can we detect iCloud sync status?
Can we redirect to the setting so users can disable it before/after enable contact synchronization?
What happens if we turn off iCloud sync? Does it copy all data to local address book?
Can we prevent creating duplicate contacts when importing from local by adding existing native contacts to a group?

**Comment by murilopereirame** [comment]
**Results of the Spike:**

**Can we detect iCloud sync status?**
- No, Apple doesn't provide any API to check iCloud status for Contact Sync

**Can we redirect to the setting so users can disable it before/after enable contact synchronization?**
- No, we can't redirect the user to a specific page inside the settings. Just if this page is contained inside our app's settings page.

**What happens if we turn off iCloud sync? Does it copy all data to local address book?**
- iOS prompt the user if they want to keep locally or remove it

**Can we prevent creating duplicate contacts when importing from local by adding existing native contacts to a group?**
- We can move contacts that belongs to the same container as Tuta contacts, e.g. iCloud contacts can be placed inside a Tuta list, but Gmail ones can't because iCloud belongs to one container and Gmail to another one.
