### ISSUE TITLE
On arch linux AUR error installing tutanota-desktop-bin "ERROR: One or more files did not pass the validity check!"

### ISSUE THREAD

**Issue by dimyself** [tutao/tutanota#6898]
I'm on version 220.240319.1-1

trying to update tutanota-desktop-bin to version: 220.240411.0-1  through the aur using yay.

> ❯ yay tuta
3 aur/mailtutan-bin 0.3.0-1 (+1 0.00) 
    An SMTP server for test and development environments written in Rust
2 aur/tutanota-desktop 225.240417.0-1 (+27 0.09) 
    Official Tutanota email client
**1 aur/tutanota-desktop-bin 220.240411.0-1 (+45 1.42) (Installed: 220.240319.1-1)**
    Official Tutanota email client
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
AUR Explicit (1): tutanota-desktop-bin-220.240411.0-1
:: PKGBUILD up to date, skipping download: tutanota-desktop-bin
  1 tutanota-desktop-bin             (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 tutanota-desktop-bin             (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: tutanota-desktop-bin 220.240411.0-1 (Fri 26 Apr 2024 05:58:41 PM CDT)
==> Retrieving sources...
  -> Found tutanota-desktop-220.240411.0.AppImage
  -> Found linux-sig-220.240411.0.bin
  -> Found tutao-pub-220.240411.0.pem
==> WARNING: Skipping verification of source file PGP signatures.
**==> Validating source files with sha512sums...
    tutanota-desktop-220.240411.0.AppImage ... FAILED
    linux-sig-220.240411.0.bin ... FAILED
    tutao-pub-220.240411.0.pem ... Passed**
**==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/user/.cache/yay/tutanota-desktop-bin 
	 context: exit status 1** 
:: (1/1) Parsing SRCINFO: tutanota-desktop-bin
==> Making package: tutanota-desktop-bin 220.240411.0-1 (Fri 26 Apr 2024 05:58:42 PM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found tutanota-desktop-220.240411.0.AppImage
  -> Found linux-sig-220.240411.0.bin
  -> Found tutao-pub-220.240411.0.pem
**==> Validating source files with sha512sums...
    tutanota-desktop-220.240411.0.AppImage ... FAILED
    linux-sig-220.240411.0.bin ... FAILED
    tutao-pub-220.240411.0.pem ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error making: tutanota-desktop-bin-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
tutanota-desktop-bin - exit status 1**

i'm on lAtest linux updates:

> ❯ uname -a
Linux userpc 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux

No idea why thye error? 

Did i miss a change with tutanota / tuta updates? I've also tried to clean build all packages when updating it

Thanks you!

**Comment by FloatingUpstream** [comment]
Same here on 6.1.82-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar 15 21:05:45 UTC 2024

**Comment by FloatingUpstream** [comment]
Ok, the sha512  obviously don't match. 

I get

`bcfd8fa28ae51a12151f992ac74957e4ac364e9d2aa0b1aabb180b6e199ebc8073fc64a3cb976300d72ba71fc50eb33ac1175cd21f4dfd0ade69c4c2c78c119f  tutanota-desktop-linux.AppImage`

and

`4e9923a87bc70f1d5d29062fa3163d799a98c8658ab9c6c533362e16e1b032902b753145c9ee6f7d0e76aaf0c26425afeb8ca142961da12905958bd589a395a9  linux-sig.bin`

which does not match
https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=tutanota-desktop-bin

At least for the, I can confirm it actually matches the  *latest* release from https://github.com/tutao/tutanota/releases/tag/tutanota-desktop-release-225.240417.0.

So what's going on?
Fundamentally, the tutanota-desktop-bin package has the problem of always pulling in the latest appimage and installer signature file from fixed URLs (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tutanota-desktop-bin). When  those files are updated, the checksums break.

So,  the arch package has to *exactly* track the latest release (which it does not at the moment), otherwise it is always going to break. Not ideal.

**Comment by FloatingUpstream** [comment]
As can be seen on https://aur.archlinux.org/packages/tutanota-desktop-bin this is a recurring issue.
The only thing that's going to fix this fundamentally is to pull in i) versioned app images, ii) versioned signature files for the verification step [1]

The only thing that Tuta could (and likely should) do here, is to publish the versioned sig files along with releases.

[1] https://tuta.com/support/#verify-desktop

**Comment by ganthern** [comment]
We're not maintaining the AUR package and have no way of helping with issues related to it.

**Comment by kib42** [comment]
We have rolled back our 225.240417.0 release back to 220.240411.0 but it looks like the signatures were not updated. The issue should not happen anymore.
