### ISSUE TITLE
Firefox asks to save password with every rest request.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#73]

**Comment by mpfau** [comment]
This is a firefox bug: Firefox displays the "Would you like to update this login?" dialog box only if the password for an Tutanota account has been stored with Firefox and the password has changed since then.

If you click on "don't update", the password manage will re-ask you "Would you like to update this login?" on every REST request of the app. The only way to stop this is to click on "update". If you don't click on "don't update" when the dialog is active (e.g. click anywhere on the screen), the dialog is hidden and not re-opened.
