### ISSUE TITLE
HTML emails have view issue

### ISSUE THREAD

**Issue by unruhe73** [tutao/tutanota#7859]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
HTML email presents white background and are not fully readable, some pieces got lost in the view. This happened for some mail I received but also from some mail I send by tutamail Android app to myself.

**To Reproduce**
1. Send an HTML to yourself

**Expected behavior**
A correct complete email with no with background and all the text shown correctly and clickable links.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Desktop Environment, if applicable (on Linux): Xfce
 - Version 4.18

**Additional context**
Same thing happen also on the Android app.
Android information:

    Device: Umidigi
    OS: Android
    Version 10

**Comment by unruhe73** [comment]
I forgot to say that I'm using dark theme.

**Comment by unruhe73** [comment]
Well, this happen also with light theme.

**Comment by charlag** [comment]
Hi, could you please be more specific which parts of the email were not displayed correctly? Would it be fine for you to send us an example?

**Comment by gvbwsrl** [comment]
> Hi, could you please be more specific which parts of the email were not displayed correctly? Would it be fine for you to send us an example?

Where can I send the mail? I don't want to expose personal emails.

Anyway, the problem is that it create a white background (why?) and then change the text colours. Some text is in black colour and some other text is in white colour, and so white text on a white background becomes hidden.
And why a white background I didn't set?

**Comment by unruhe73** [comment]
> Hi, could you please be more specific which parts of the email were not displayed correctly? Would it be fine for you to send us an example?

Where can I send the mail? I don't want to expose personal emails.

Anyway, the problem is that it create a white background (why?) and then change the text colours. Some text is in black colour and some other text is in white colour, and so white text on a white background becomes hidden.
And why a white background I didn't set?

**Comment by charlag** [comment]
When we detect that there is some background or text color applied to email we add a fallback which sets the background to white and the text color to black. It is just a default, if the email overrides specific places, that takes priority. It works this way because white background is the expectation from email clients in most cases.

If you could send your example to hello@tutao de and mention that we asked for it in this issue.

**Comment by unruhe73** [comment]
> When we detect that there is some background or text color applied to email we add a fallback which sets the background to white and the text color to black. It is just a default, if the email overrides specific places, that takes priority. It works this way because white background is the expectation from email clients in most cases.
> 
> If you could send your example to hello@tutao de and mention that we asked for it in this issue.
I did not apply any colour. I simply copied and pasted a text with some URL inside and sent to myself. It worked. When I did the same, adding more recipients (including me too), it didn't work on the Tuta client when I received my email. I tried to get the source of the email as I could do on Thunderbird for other email provider and on Tuta I cannot get the source. I wanted to check if the HTML had some issue inside but I couldn't. I'me sending the email right now.

**Comment by unruhe73** [comment]
Using the browser the problem is not there. Is this a known app issue? I'm a paying customer I'd like to use Desktop and Android app to manage the mail with Tuta.

**Comment by unruhe73** [comment]
The browser Is Firefox with dark theme and I use Tuta dark theme.

**Comment by unruhe73** [comment]
The theme (dark or light) is not the problem. It's happening on any theme.

**Comment by charlag** [comment]
You are saying that parts of email are not displayed and it's happening on both light and dark themes, is this right?

**Comment by BijinDev** [comment]
Hello, Thank you for your patience while we looked into this issue. After thoroughly investigating, we have found that this behavior is actually a feature not a bug. The HTML text is designed to support multiple colors and due to this, setting a background color to black is not feasible. This is consistent with how other mail providers like proton and outlook handle this scenario. Thank you for your understanding.

**Comment by unruhe73** [comment]
Well, I sent the same email from Proton and I get no issue or problem with strange colours background that hide the text in it, so I think I'm going to use Proton as mail provider and you can close the issue.

**Comment by charlag** [comment]
We are sorry to hear that, if you think we missed something while testing please let us know.

**Comment by unruhe73** [comment]
> We are sorry to hear that, if you think we missed something while testing please let us know.

Really?
"we have found that this behavior is actually a feature not a bug". A feature to hide the text inside an email using the same colour of the background? A feature? Wow. Wow. Wow. I just purchased 2 years with Proton Unlimited and I stopped to have issues with email using Proton. I gave you a possibility, but I suppose I was wrong. Don't worry I'm more happy with Proton.
