### ISSUE TITLE
app password is required twice to use access/use the mailbox

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#7873]
**Describe the bug**
Since the last update the app password is triggered once when logging in and once after the login (email list is already visible).

**To Reproduce**
1. Add app password as unlock method
2. Log out/Open a new instance
3. Log into any user
4. See issue

**Desktop (please complete the following information):**
 Reproduced on Windows 11 and Ubuntu 22.04.4 LTS

## Test notes

- [ ] On a fresh install, enable app password (Login -> Unlock method). Ensure that logging in only asks for your app password once in the account menu and then never again.
- [ ] Disable app password. This may ask for the app password one last time, as expected. Ensure that logging in still works once app password is disabled.

**Comment by charlag** [comment]
Together with @paw-hub and @vitoreiji we figured why this happens and why only to some accounts.

It seems like we re-encrypted `encryptedPassphraseKey` on every login. For newer sessions (which use AES256 `accessKey`) this will be done with a random `IV`. This won't match the stored `encryptedPassphraseKey` and we would try to store it again.

We don't have a good solution for re-encrypting it (because it depends on KDF and we don't know the previous KDF type), but we can easily replace `encryptedPassphrase` and `encryptedPassphraseKey` locally without going through keychain, as we do when the change the password already.
