### ISSUE TITLE
Crash when adding attachments on iPadOS

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#7914]
When adding an attachment, the app will crash the moment the paperclip icon is tapped.

We were able to reproduce this on our test iPad where it always happens; no crash on our iPhone, though.

Workaround: You can attach a file by using "Share" on the file itself and share with the Tuta app. It will create a new mail with the file attached.

## Test note:
- [ ] Adding attachments works on iPad
- [ ] Adding attachments works on iPhone

**Time spent: 3h**

**Comment by MatthewPhilipStadler** [comment]
I use Tuta on my iPad app. Can you clarify (or confirm)—has this issue been repaired? Can I now click the paper-clip icon without crashing the app? It is unclear to me if the issue has been repaired or if we are expected to use the work-around (above) in perpetuity.

**Comment by hrb-hub** [comment]
> I use Tuta on my iPad app. Can you clarify (or confirm)—has this issue been repaired? Can I now click the paper-clip icon without crashing the app? It is unclear to me if the issue has been repaired or if we are expected to use the work-around (above) in perpetuity.

Hi @MatthewPhilipStadler , thank you for your patience,
While we have a fix for this issue, the fix hasn't yet been released. However, it should be included in a next release.

**Comment by MatthewPhilipStadler** [comment]
I don' know how long it takes to make the next release. If there is any simple way to change the outcome of touching the paperclip icon—so instead of crashing the app, nothing happens—having that soon would be great. It's a significant problem for me; it's hard to overcome the routine of touching the paperclip; it's  also impossible to send multiple attachments. For me, these are serious difficulties. Thanks for all the community help here, much appreciated. Matthew
