### ISSUE TITLE
Message read status not syncing properly with web client in iOS, most notable in folders

### ISSUE THREAD

**Issue by JSkier21** [tutao/tutanota#8041]
- [ ✔️ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ✔️ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Message read status across iOS devices is not syncing with the web application, very delayed or broken. This appears to be one way, for example, if I click mark the message as read on iOS, it will almost instantly show up in the web application on the browser. However, this is not the case at all when marking a message read in the browser to iOS devices. Note, I do have a couple of dozen mailbox rules, and also folders. Quitting and restarting the iOS app a couple of times gets things to sync in the root inbox, however, not the case with any folders I can see. 

I have tried leaving the app open, previously hoping things would sync, It's been several hours, and they don't until I manually mark them as read in iOS. 

**To Reproduce**
1. Go to Tuta web application. Find a folder with a few unread messages on it. Mark them as read
2. Open the Tuta iOS app, let it connect and allegedly sync
3. Check the folder where you marked messages read on the web, they will be out of sync and likely show many of those messages as unread, despite the contrary from all being marked as read in the web application

**Expected behavior**
Inbox and folders should sync relatively quickly across platforms. When I mark a message as read in the web applications, it should show up relatively quickly as marked read on iOS devices. 

Changes strictly made on Apple devices, do, in fact, sync the read status correctly. With the web application, I would expect changes in the browser to sync across to iOS. However, they do not.

**Screenshots**
Web application showing messages as marked as read (red = read, Freudian slip 😅):
![image](https://github.com/user-attachments/assets/729f1126-6fb7-4a3b-8fe1-4704390b61cd)
iOS application, same folder, showing 3 of the same messages marked as unread (note that badge count is accurate at zero though):
![image](https://github.com/user-attachments/assets/0dbfb463-9afa-4f35-a214-f1a0e85a72d7)

**Smartphone (please complete the following information):**
 - Device: iPhone 15, iPad Mini, computer web browser
 - OS: iOS 18.1.1 on both devices, latest Firefox and Chrome with Tuta app up-to-date as of 11/26/24
 - Version: Tuta 253.241126.2 (problem has been ongoing with previous versions for a few weeks, working with support on this)

**Additional context**
Other than the above, not much else I have, happy to provide any details if you ask. 

## Test notes
- [ ] Have the same account on two clients, one being on mobile, the other on desktop or web.
- [ ] Make sure mobile is logged out.
- [ ] From desktop or web send an email to yourself and mark it as read.
- [ ] Login on mobile and see that email has the correct read status.
  - [ ] When mail is within cached range (most cases).
  - [ ] When mail is outside cached range. This happens when the mail belongs to a newly created mail bag with mail list that is not cached by the client (might be easier to test this locally by reducing mailbag's max size).
    - [ ] Again, make sure mobile client is logged out.
    - [ ] From desktop, send multiple mails until current mail bag limit is reached and a new mail bag is created.
    - [ ] From desktop mark a few mails from new mail bag as read.
    - [ ] Login on mobile and see mails have the correct read status.

**Comment by charlag** [comment]
We did debug a bit more and we were puzzled why email is not in the cached range since mail indexer does use that range and `OfflineStorageCleaner` does not delete those lists completely (whether it should is another question).

We found one such case: when there's a new mail bag, the app would not a cached range for it since it never did mail indexing for it.

We experimented with adding a fallback check for a single entity but it adds ~3ms delay on Android and ~8ms delay on desktop for each entity update which quickly adds up and we don't think that we want to go with this solution.

We are trying to think of more options, e.g. storing this not as a mail entity but they all have drawbacks.

**Comment by alstr** [comment]
Possibly related to the long-standing issue https://github.com/tutao/tutanota/issues/4265

**Comment by alstr** [comment]
> I wanted to add, as a paying customer, I worked with support initially on this. They were very dismissive, and didn't have much desire to work on this. This is very frustrating to see that Tuta seems to be focused on heavy marketing, and making more products (a separate calendar, for example), when they should be focusing on the core, making the existing e-mail service reliable and solid enough to work as expected.

100%. Support only seem to be interested in workarounds and the outlook of Tuta is almost entirely focused on the 'next big thing'. I know this is not directly related to the issue at hand, so I won't go into it further - but previous constructive efforts have felt like shouting into the void anyway, and patience is wearing thing. #4265 is years old and hasn't had a Tuta response since 2023.
