### ISSUE TITLE
Database error after update to version v252.241122.0

### ISSUE THREAD

**Issue by jackwilliams79** [tutao/tutanota#8044]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After updating to version v252.241122.0 on Android, the following error message is shown everytime the app is opened:

> Feedback v252.241122.0 - ProgrammingError - UNKNOWN - androidClient: android Type: UNKNOWN Tutanota version: 252.241122.0 Timestamp (UTC): Wed, 27 Nov 2024 16:31:08 GMT User agent: Mozilla/5.0 (Linux; Android 15; Pixel 8 Build/AP3A.241105.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.81 Mobile Safari/537.36 ProgrammingError Error message: You forgot to migrate your databases! sys.version should be >= 114 but in db it is 112 Stacktrace: ProgrammingError: You forgot to migrate your databases! sys.version should be >= 114 but in db it is 112 at Hc.checkStateAfterMigrations (https://assets.tutanota.com/mail-worker.js:23:63094) at async Hc.migrate (https://assets.tutanota.com/mail-worker.js:23:62872) at async Ws.init (https://assets.tutanota.com/mail-worker.js:1:19717) at async pc.getStorage (https://assets.tutanota.com/mail-worker.js:23:50139) at async pc.initialize (https://assets.tutanota.com/mail-worker.js:23:49906) at async qo.initCache (https://assets.tutanota.com/mail-worker.js:23:10521) at async qo.resumeSession (https://assets.tutanota.com/mail-worker.js:23:7331)

**To Reproduce**
1. Not sure how to reproduce an app update on Android
2. Just start the app
3. Error message occurs

**Expected behavior**
Normal functioning app. No error message

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8
 - OS: Android
 - Version: 15

**Additional context**

**Comment by dillymyers** [comment]
Got the same problem after updating my app through F-Droid just now, can't see any other problems though

**Comment by Gitchick57** [comment]
What kind of database error?  I have been experiencing  miscellaneous error messages upon opening the app since late September.



Nov 27, 2024, 4:22 PM by ***@***.***:

**Comment by Piscium** [comment]
Just updated from F-Droid, got the same error message as the OP.
I also get the message every time I start the app. I had no issue before this update. I am also on Pixel 8.
Despite the error message things seem more or less normal, I have not done a full test to see if anything is broken.
The error message looks scary though, especially if the bit about the databases is at the server rather than the Android client, as then I could lose messages.

**Comment by charlag** [comment]
Hi, sorry about the issue, F-Droid tag was pointing to the version without the fix which is our oversight.

Upgrading to the next release (253.241126.2) or simply deleting your credentials and logging in again should automatically fix it.

I will close the issue now as it should be fixed by upgrading to the next app version.

**Comment by jackwilliams79** [comment]
@charlag Thanks for the info. Good to know that a fix is already implemented. In F-Droid the newer version is currently not yet available. In the meantime, logging out of the app and logging back in does really solve the problem.
