### ISSUE TITLE
The body of the email is not displayed.

### ISSUE THREAD

**Issue by DemetrDs** [tutao/tutanota#8115]
The body of the email is not displayed. Not in any of the browsers.
![R5gYTYVxEV](https://github.com/user-attachments/assets/454c1124-9cdf-4f81-a76e-b96a33490f62)

**Comment by hrb-hub** [comment]
Thank you for the report, @DemetrDs 
Could you please use one of the available issue templates to provide us with more details as we cannot really fix an issue unless we can reproduce it.

Please find the web app report template below:

----

- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by DemetrDs** [comment]
Problem solved. Must be related to your network infrastructure. Changing your ISP solved the problem.
