### ISSUE TITLE
Label function disappeared.

### ISSUE THREAD

**Issue by 426Cuda** [tutao/tutanota#8120]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).

- [x] I've searched and did not find a similar issue.

**Describe the bug**
Two updates ago the Label function appeared.  I tested it with one email, and it worked fine.  I left the label on the email because it was important to me.  The last update I received, the Label function was gone.  I cannot delete the email with the label on.
**To Reproduce**
1. Go to 'email with label on it'
2. Click on 'Trash can to delete the email'
3. Nothing happens, email is not removed to the trash folder

**Expected behavior**
The email should be moved from the inbox to the trash folder
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Desktop Environment, if applicable (on Linux)
 - Version [11]

**Additional context**

**Comment by hrb-hub** [comment]
Hi @426Cuda 
The label functionality disappeared because labels were accidentally released to the public earlier than planned.
Sorry you're having issues deleting previously labelled mail. To resolve this we need your email address, so please contact support if you're a paying customer, or send us an email at `hello[at]tutao.de` if you're on the free plan, please make sure to mention this github issue when you do.

Cheers :)
