### ISSUE TITLE
Several severe problems with new Version of Tutanota. Worked fine before new version.

### ISSUE THREAD

**Issue by sfd99** [tutao/tutanota#855]
Old version always worked fine.

**Problem 1)** Takes a _looong time_ to login
(progess bar just keeps the message: "Logging in"..)

**Problem 2)**  Replying to a received email
 is now _impossible_.
(progess bar just keeps the message: 
"Your message is being sent"..forever. Nothing is sent!!).

**Problem 3)** If a received email message has a **PDF attachment**,
you can not open it. Nothing happens....

new UI is very cool.
_Unfortunately_, (at least in my case),
Tutanota has become non-operational.
I can not use it anymore
unless these compatibility issues are fixed...
Used to work 100% fine 
_before_ the Tutanota "upgrade"... :(

 **my config:  
 - UbuntuLinux 14.04 LTS 32-bit
 - Pale Moon browser 27.9.4 (a good Firefox-compatible browser)**

**SFd99
San Francisco**

**Comment by charlag** [comment]
HI
Unfortunately, Pale Moon is far from "Firefox-combatible" at this time. Many users have reported indexing-related problems with PaleMoon because they have never implemented Promises according to the spec. 
Your version is particularly old (current one is  28.2.1).
I can propose you to update PaleMoon or try another browser. Not only will it be more secure for you but will also make our life much easier.
Please report if error persists in other configurations.

**Comment by sfd99** [comment]
Thanks Charla for the quick response!.

Q: any chance of a URL to use the _previous_ version of **Tutanota**?.
It worked so graat with my current setup
and did all I needed...
Thanks -
SFd99
San Francisco

**Comment by charlag** [comment]
We are going to disable old clients completely after some time because they cause a lot of technical difficulties so it's not a solution.
New client does everything that old client did plus more and faster.

**Comment by sfd99** [comment]
charlag: 
Ok, Understood.
Can I get a temp "prev. version" URL 
just for the time being, (temporarily),
while I upgrade to a different new browser?.
