### ISSUE TITLE
FOSS Android Application

### ISSUE THREAD

**Issue by aloisdg** [tutao/tutanota#89]
Hello,

Would it be possible to open android application' source?
I would like to being able to download it from F-Droid instead of google.

If there is a better place to post this tell me :)

Thank you

**Comment by mpfau** [comment]
Sure! We plan to release the new client to F-Droid, too!

**Comment by picsi** [comment]
@mpfau previously the problem was that the app used cordova, which F-Droid servers couldn't build. Has this situation changed?

**Comment by mpfau** [comment]
Yes, the new app is not based on cordova anymore...

**Comment by shiftee** [comment]
The old app which seems to have disappeared from F-Droid is no longer able to connect since last night

**Comment by armhub** [comment]
Tutanota was not available in F-Droid at all.

**Comment by shiftee** [comment]
Ok, I must have found the download link somewhere, but I could have sworn it was in F-Droid.

I have found the 2.15 version which works for me.

Thanks

**Comment by prog-amateur** [comment]
Hello, this is unclear. It is said that tutanota would be on F-Droid on 2017, but now in almost mid-2018, there is still nothing, so what is the main issue you meet to upload it in this store ? 

Because on the web site (https://tutanota.uservoice.com/knowledgebase/articles/483300-where-can-i-get-the-tutanota-app) the download apk is available but is not man-in-the-middle proof. F-Droid is man-in-the-middle proof. 
Anyway, thanks for the good job, and please feedback.

**Comment by bedhub** [comment]
3764b47
06025d3
51456d3

**Comment by picsi** [comment]
Being tracked at https://gitlab.com/fdroid/rfp/issues/504

**Comment by charlag** [comment]
We're merged
https://gitlab.com/fdroid/fdroiddata/merge_requests/3468

**Comment by picsi** [comment]
Good job and thank you for working on this!

**Comment by testbird** [comment]
Hey, congratulations to you for pulling the f-droid release with notifications build-in!

In case you haven't come accross this, it might be in your interests:
https://gitlab.com/foss-push/planning

**Comment by tometchy** [comment]
Just out of curiosity, what did you choose instead cordova? :)

**Comment by sm4rk0** [comment]
Server Sent Events (SSE)?
https://github.com/tutao/tutanota/issues/386
