### ISSUE TITLE
npm audit: found 9 vulnerabilities (8 low, 1 high)

### ISSUE THREAD

**Issue by vladimiry** [tutao/tutanota#906]
```
found 9 vulnerabilities (8 low, 1 high) in 4869 scanned packages
  9 vulnerabilities require manual review. See the full report for details.
```

**Comment by charlag** [comment]
We've checked that when we did internal security review.
They're all dev dependencies and most of them are caused by JS server and hot reloading things which are not event needed for production builds.

**Comment by vladimiry** [comment]
I understand that, but dev dependencies also matter as vulnerabilities there might affect developers machines when they run/build the project locally. Besides hacked dev dependency is potentially capable to inject malicious stuff into the final production build during the build process.

Replacing the potentially vulnerable modules with alternatives might be a viable option, npm repository is full of fancy stuff :)

**Comment by jchook** [comment]
Update to this issue (as of v3.57.6)

```
found 11 vulnerabilities (10 low, 1 high) in 6601 scanned packages
  1 vulnerability requires semver-major dependency updates.
  10 vulnerabilities require manual review. See the full report for details.
```

I understand completely the low severity of these flags in context, but I decided to bump this issue since it negatively affects the first impression of first-time users.

The flags stem from 3 sub-dependencies of `chokidar-socket-emitter`.

- [parsejson](https://nodesecurity.io/advisories/528) (high)
- [debug](https://nodesecurity.io/advisories/534)
- [braces](https://nodesecurity.io/advisories/786)

To fix: 

- `parsejson` must resolve https://github.com/galkn/parsejson/issues/4
- `socket.io` must resolve their issues

Or we can remove the dependency on chokidar-socket-emitter.

**Comment by charlag** [comment]
I updated `chokidar` on a branch yesterday but I didn't touch `chokidar-socket-emitter` because, well we use it and we cannot replace it which is in turn because of the deprecated Systemjs version and associated libraries which we plan to migrate away from in any case.
