### ISSUE TITLE
Distribute the desktop application as a flatpak on flathub

### ISSUE THREAD

**Issue by 0x5a17ed** [tutao/tutanota#986]
As a Gnome user it would be nice to install the Tutanota desktop application from the [Gnome Software Center](https://wiki.gnome.org/Apps/Software) as a [Flatpak](https://flatpak.org/) distributed via [flathub](https://flathub.org/apps/search/tutanota).

**Comment by Jacalz** [comment]
+1 from me
The huge pros with this is that it's a secure sandboxed way of delivering applications that auto update without user interaction. Really the safest and easiest way to support all Linux distros...

**Comment by charlag** [comment]
Hey!
We don't use GitHub for feature requests, but... I want Flatpak myself. There are instructions in Flatpak docs specifically for Electron. If someone would try to make it work, it would be a huge support to us. Build scripts are in the repo so feel free to experiment.

**Comment by Jacalz** [comment]
@charlag The readme actually states that github is the issue and feature tracker 😉

**Comment by charlag** [comment]
Oops, we should say that we would like people to request features on Reddit or via email, otherwise it's hard to handle it here
Sorry for the confusion, this thing should be opened anyway!

**Comment by 0x5a17ed** [comment]
> We don't use GitHub for feature requests

Sorry, my bad, I ignored the repository Readme and went straight to the issue tracker to look there if it was already suggest to distribute the desktop application through flatpak or not. 

I didn't expect such a note in the Readme since I'm used to repository owners using the GitHub issue template feature to tell users what to put in an issue and what not. :sweat_smile:

> I want Flatpak myself

I'm glad that the request is still accepted though. I myself as a user find the Flatpak way of distributing and updating software very convenient for desktop applications. It works across all Linux distributions that pack flatpak itself and works on GNOME and KDE.

> There are instructions in Flatpak docs specifically for Electron. If someone would try to make it work, it would be a huge support to us. Build scripts are in the repo so feel free to experiment.

Unfortunately I have no experience in building/developing electron apps nor distributing software through Flatpak. So I'm afraid that, as much as I would love to, I can't help out on this part here.

**Comment by valentindavid** [comment]
I have opened a pull request on flathub to add tutanota.
https://github.com/flathub/flathub/pull/918

Do Tutanota developers want to be involved in this?

**Comment by x80486** [comment]
...shouldn't this be closed?

**Comment by charlag** [comment]
Indeed, thanks

**Comment by 4jNsY6fCVqZv** [comment]
@charlag There is a problem with publishing via Flathub. Flathub is a platform that also offers proprietary packages. Since I switched to Linux to only find free software in my Software Center, installing the Tutanota Flatpak unfortunately takes me away from this goal. When I install an app via Flathub, the proprietary apps I don't want are suddenly displayed in my Software Center. I don't want that. Therefore I ask you to offer an official version as a download e.g. via your website as an alternative for people who are looking for 100% Free Software. What do you think?

**Comment by x80486** [comment]
Can't you just look at the `License` tag while using the `GNOME Software Center`? There are ways to find if the application you are about to install meets certain criteria(s).

If your problem is the _purism_ about distribution channels, then that's a different story.

**Comment by charlag** [comment]
@4jNsY6fCVqZv the only supported client currently is AppImage one: https://tutanota.com/faq/#desktop
Flathub will be released later

**Comment by 4jNsY6fCVqZv** [comment]
> If your problem is the purism about distribution channels, then that's a different story.

@x80486 Exactly, it's more that way. 
https://github.com/flathub/flathub/issues/691
 That would indeed be a solution to my concerns. However, since there hasn't been any activity in this direction for over a year and no milestone, developer or label has been assigned to this idea, I'd rather ask the respective developers of the apps I use myself directly. For something to happen. Can you imagine providing an alternative to Flathub as soon as you take care of your Flatpak distribution? @charlag

**Comment by 4jNsY6fCVqZv** [comment]
> If your problem is the purism about distribution channels, then that's a different story.

@x80486 Exactly, it's more that way. 
https://github.com/flathub/flathub/issues/691
 That would indeed be a solution to my concerns. However, since there hasn't been any activity in this direction for over a year and no milestone, developer or label has been assigned to this idea, I'd rather ask the respective developers directly.

@charlag Can you imagine providing an alternative to Flathub as soon as you take care of your Flatpak distribution?

**Comment by armhub** [comment]
There are still some fixes needed.
